GFX_DEP := \
	data/gfx/dprint/0.rgba16.h \
	data/gfx/dprint/1.rgba16.h \
	data/gfx/dprint/2.rgba16.h \
	data/gfx/dprint/3.rgba16.h \
	data/gfx/dprint/4.rgba16.h \
	data/gfx/dprint/5.rgba16.h \
	data/gfx/dprint/6.rgba16.h \
	data/gfx/dprint/7.rgba16.h \
	data/gfx/dprint/8.rgba16.h \
	data/gfx/dprint/9.rgba16.h \
	data/gfx/dprint/a.rgba16.h \
	data/gfx/dprint/b.rgba16.h \
	data/gfx/dprint/c.rgba16.h \
	data/gfx/dprint/d.rgba16.h \
	data/gfx/dprint/e.rgba16.h \
	data/gfx/dprint/f.rgba16.h \
	data/gfx/dprint/g.rgba16.h \
	data/gfx/dprint/h.rgba16.h \
	data/gfx/dprint/i.rgba16.h \
	data/gfx/dprint/k.rgba16.h \
	data/gfx/dprint/l.rgba16.h \
	data/gfx/dprint/m.rgba16.h \
	data/gfx/dprint/n.rgba16.h \
	data/gfx/dprint/o.rgba16.h \
	data/gfx/dprint/p.rgba16.h \
	data/gfx/dprint/r.rgba16.h \
	data/gfx/dprint/s.rgba16.h \
	data/gfx/dprint/t.rgba16.h \
	data/gfx/dprint/u.rgba16.h \
	data/gfx/dprint/w.rgba16.h \
	data/gfx/dprint/y.rgba16.h \
	data/gfx/dprint/squote.rgba16.h \
	data/gfx/dprint/dquote.rgba16.h \
	data/gfx/dprint/multiply.rgba16.h \
	data/gfx/dprint/coin.rgba16.h \
	data/gfx/dprint/mario.rgba16.h \
	data/gfx/dprint/star.rgba16.h \
	data/gfx/staff/3.rgba16.h \
	data/gfx/staff/4.rgba16.h \
	data/gfx/staff/6.rgba16.h \
	data/gfx/staff/a.rgba16.h \
	data/gfx/staff/b.rgba16.h \
	data/gfx/staff/c.rgba16.h \
	data/gfx/staff/d.rgba16.h \
	data/gfx/staff/e.rgba16.h \
	data/gfx/staff/f.rgba16.h \
	data/gfx/staff/g.rgba16.h \
	data/gfx/staff/h.rgba16.h \
	data/gfx/staff/i.rgba16.h \
	data/gfx/staff/j.rgba16.h \
	data/gfx/staff/k.rgba16.h \
	data/gfx/staff/l.rgba16.h \
	data/gfx/staff/m.rgba16.h \
	data/gfx/staff/n.rgba16.h \
	data/gfx/staff/o.rgba16.h \
	data/gfx/staff/p.rgba16.h \
	data/gfx/staff/q.rgba16.h \
	data/gfx/staff/r.rgba16.h \
	data/gfx/staff/s.rgba16.h \
	data/gfx/staff/t.rgba16.h \
	data/gfx/staff/u.rgba16.h \
	data/gfx/staff/v.rgba16.h \
	data/gfx/staff/w.rgba16.h \
	data/gfx/staff/x.rgba16.h \
	data/gfx/staff/y.rgba16.h \
	data/gfx/staff/z.rgba16.h \
	data/gfx/staff/period.rgba16.h \
	data/gfx/message/0.ia4.h \
	data/gfx/message/1.ia4.h \
	data/gfx/message/2.ia4.h \
	data/gfx/message/3.ia4.h \
	data/gfx/message/4.ia4.h \
	data/gfx/message/5.ia4.h \
	data/gfx/message/6.ia4.h \
	data/gfx/message/7.ia4.h \
	data/gfx/message/8.ia4.h \
	data/gfx/message/9.ia4.h \
	data/gfx/message/u_a.ia4.h \
	data/gfx/message/u_b.ia4.h \
	data/gfx/message/u_c.ia4.h \
	data/gfx/message/u_d.ia4.h \
	data/gfx/message/u_e.ia4.h \
	data/gfx/message/u_f.ia4.h \
	data/gfx/message/u_g.ia4.h \
	data/gfx/message/u_h.ia4.h \
	data/gfx/message/u_i.ia4.h \
	data/gfx/message/u_j.ia4.h \
	data/gfx/message/u_k.ia4.h \
	data/gfx/message/u_l.ia4.h \
	data/gfx/message/u_m.ia4.h \
	data/gfx/message/u_n.ia4.h \
	data/gfx/message/u_o.ia4.h \
	data/gfx/message/u_p.ia4.h \
	data/gfx/message/u_q.ia4.h \
	data/gfx/message/u_r.ia4.h \
	data/gfx/message/u_s.ia4.h \
	data/gfx/message/u_t.ia4.h \
	data/gfx/message/u_u.ia4.h \
	data/gfx/message/u_v.ia4.h \
	data/gfx/message/u_w.ia4.h \
	data/gfx/message/u_x.ia4.h \
	data/gfx/message/u_y.ia4.h \
	data/gfx/message/u_z.ia4.h \
	data/gfx/message/l_a.ia4.h \
	data/gfx/message/l_b.ia4.h \
	data/gfx/message/l_c.ia4.h \
	data/gfx/message/l_d.ia4.h \
	data/gfx/message/l_e.ia4.h \
	data/gfx/message/l_f.ia4.h \
	data/gfx/message/l_g.ia4.h \
	data/gfx/message/l_h.ia4.h \
	data/gfx/message/l_i.ia4.h \
	data/gfx/message/l_j.ia4.h \
	data/gfx/message/l_k.ia4.h \
	data/gfx/message/l_l.ia4.h \
	data/gfx/message/l_m.ia4.h \
	data/gfx/message/l_n.ia4.h \
	data/gfx/message/l_o.ia4.h \
	data/gfx/message/l_p.ia4.h \
	data/gfx/message/l_q.ia4.h \
	data/gfx/message/l_r.ia4.h \
	data/gfx/message/l_s.ia4.h \
	data/gfx/message/l_t.ia4.h \
	data/gfx/message/l_u.ia4.h \
	data/gfx/message/l_v.ia4.h \
	data/gfx/message/l_w.ia4.h \
	data/gfx/message/l_x.ia4.h \
	data/gfx/message/l_y.ia4.h \
	data/gfx/message/l_z.ia4.h \
	data/gfx/message/arrow.ia4.h \
	data/gfx/message/exclaim.ia4.h \
	data/gfx/message/coin.ia4.h \
	data/gfx/message/multiply.ia4.h \
	data/gfx/message/paren_l.ia4.h \
	data/gfx/message/paren_rl.ia4.h \
	data/gfx/message/paren_r.ia4.h \
	data/gfx/message/tilde.ia4.h \
	data/gfx/message/period.ia4.h \
	data/gfx/message/percent.ia4.h \
	data/gfx/message/bullet.ia4.h \
	data/gfx/message/comma.ia4.h \
	data/gfx/message/apostrophe.ia4.h \
	data/gfx/message/question.ia4.h \
	data/gfx/message/star.ia4.h \
	data/gfx/message/star_outline.ia4.h \
	data/gfx/message/quote_l.ia4.h \
	data/gfx/message/quote_r.ia4.h \
	data/gfx/message/colon.ia4.h \
	data/gfx/message/underscore.ia4.h \
	data/gfx/message/hyphen.ia4.h \
	data/gfx/message/ampersand.ia4.h \
	data/gfx/message/hash.ia4.h \
	data/gfx/message/button_a.ia4.h \
	data/gfx/message/button_b.ia4.h \
	data/gfx/message/button_c.ia4.h \
	data/gfx/message/button_z.ia4.h \
	data/gfx/message/button_r.ia4.h \
	data/gfx/message/button_cu.ia4.h \
	data/gfx/message/button_cd.ia4.h \
	data/gfx/message/button_cl.ia4.h \
	data/gfx/message/button_cr.ia4.h \
	data/gfx/message/tf.rgba16.h \
	data/gfx/message/slight_smile.rgba16.h \
	data/gfx/message/beaned.rgba16.h \
	data/gfx/message/pensive.rgba16.h \
	data/gfx/camera/camera.rgba16.h \
	data/gfx/camera/lakitu.rgba16.h \
	data/gfx/camera/cross.rgba16.h \
	data/gfx/camera/up.rgba16.h \
	data/gfx/camera/down.rgba16.h \
	data/select.h \
	data/en_us.h \
	data/course.h \
	data/level.h \
	data/gfx/number/gfx.vtx.h \
	data/gfx/number/gfx.h \
	data/gfx/shadow/circle.ia8.h \
	data/gfx/shadow/square.ia8.h \
	data/gfx/wipe/star.ia8.h \
	data/gfx/wipe/circle.ia8.h \
	data/gfx/wipe/mario.ia8.h \
	data/gfx/wipe/bowser.ia8.h \
	data/gfx/scroll/water_0.rgba16.h \
	data/gfx/scroll/water_1.rgba16.h \
	data/gfx/scroll/water_2.rgba16.h \
	data/gfx/scroll/mist.ia16.h \
	data/gfx/scroll/lava.rgba16.h \
	data/gfx/minimap/arrow.ia8.h \
	data/gfx/error/1.i4.h \
	data/gfx/error/2.i4.h \
	data/gfx/hypercam/hypercam.i4.h \
	data/gfx/wincursor/wincursor.ia4.h

SETUP_DEP := \
	data/setup.rgba16.h

AVATAR_DEP := \
	data/avatar.rgba32.h

PLAYER_DEP := \
	shape/player/mario/metal.rgba16.h \
	shape/player/mario/button.rgba16.h \
	shape/player/mario/logo.rgba16.h \
	shape/player/mario/sideburn.rgba16.h \
	shape/player/mario/moustache.rgba16.h \
	shape/player/mario/eye_open.rgba16.h \
	shape/player/mario/eye_half.rgba16.h \
	shape/player/mario/eye_closed.rgba16.h \
	shape/player/mario/eye_left.rgba16.h \
	shape/player/mario/eye_right.rgba16.h \
	shape/player/mario/eye_up.rgba16.h \
	shape/player/mario/eye_down.rgba16.h \
	shape/player/mario/eye_dead.rgba16.h \
	shape/player/mario/wing_l.rgba16.h \
	shape/player/mario/wing_r.rgba16.h \
	shape/player/mario/metal_wing_l.rgba16.h \
	shape/player/mario/metal_wing_r.rgba16.h \
	shape/player/mario/h_waist.vtx.h \
	shape/player/mario/h_waist.h \
	shape/player/mario/h_uarmL.vtx.h \
	shape/player/mario/h_uarmL.h \
	shape/player/mario/h_larmL.vtx.h \
	shape/player/mario/h_larmL.h \
	shape/player/mario/h_fistL.vtx.h \
	shape/player/mario/h_fistL.h \
	shape/player/mario/h_uarmR.vtx.h \
	shape/player/mario/h_uarmR.h \
	shape/player/mario/h_larmR.vtx.h \
	shape/player/mario/h_larmR.h \
	shape/player/mario/h_fistR.vtx.h \
	shape/player/mario/h_fistR.h \
	shape/player/mario/h_thighL.vtx.h \
	shape/player/mario/h_thighL.h \
	shape/player/mario/h_shinL.vtx.h \
	shape/player/mario/h_shinL.h \
	shape/player/mario/h_shoeL.vtx.h \
	shape/player/mario/h_shoeL.h \
	shape/player/mario/h_thighR.vtx.h \
	shape/player/mario/h_thighR.h \
	shape/player/mario/h_shinR.vtx.h \
	shape/player/mario/h_shinR.h \
	shape/player/mario/h_shoeR.vtx.h \
	shape/player/mario/h_shoeR.h \
	shape/player/mario/h_torso0.vtx.h \
	shape/player/mario/h_torso2.vtx.h \
	shape/player/mario/h_torso1.vtx.h \
	shape/player/mario/h_torso0.h \
	shape/player/mario/h_torso1.h \
	shape/player/mario/h_torso2.h \
	shape/player/mario/h_cap0.vtx.h \
	shape/player/mario/h_cap1.vtx.h \
	shape/player/mario/h_cap2.vtx.h \
	shape/player/mario/h_cap3.vtx.h \
	shape/player/mario/h_cap5.vtx.h \
	shape/player/mario/h_cap4.vtx.h \
	shape/player/mario/h_cap6.vtx.h \
	shape/player/mario/h_cap0.h \
	shape/player/mario/h_cap1.h \
	shape/player/mario/h_cap2.h \
	shape/player/mario/h_cap3.h \
	shape/player/mario/h_cap4.h \
	shape/player/mario/h_cap5.h \
	shape/player/mario/h_cap6.h \
	shape/player/mario/h_hair0.vtx.h \
	shape/player/mario/h_hair2.vtx.h \
	shape/player/mario/h_hair1.vtx.h \
	shape/player/mario/h_hair3a.vtx.h \
	shape/player/mario/h_hair4.vtx.h \
	shape/player/mario/h_hair3b.vtx.h \
	shape/player/mario/h_hair0.h \
	shape/player/mario/h_hair1.h \
	shape/player/mario/h_hair2.h \
	shape/player/mario/h_hair3a.h \
	shape/player/mario/h_hair3b.h \
	shape/player/mario/h_hair4.h \
	shape/player/mario/m_waist.vtx.h \
	shape/player/mario/m_waist.h \
	shape/player/mario/m_uarmL.vtx.h \
	shape/player/mario/m_uarmL.h \
	shape/player/mario/m_larmL.vtx.h \
	shape/player/mario/m_larmL.h \
	shape/player/mario/m_fistL.vtx.h \
	shape/player/mario/m_fistL.h \
	shape/player/mario/m_uarmR.vtx.h \
	shape/player/mario/m_uarmR.h \
	shape/player/mario/m_larmR.vtx.h \
	shape/player/mario/m_larmR.h \
	shape/player/mario/m_fistR.vtx.h \
	shape/player/mario/m_fistR.h \
	shape/player/mario/m_thighL.vtx.h \
	shape/player/mario/m_thighL.h \
	shape/player/mario/m_shinL.vtx.h \
	shape/player/mario/m_shinL.h \
	shape/player/mario/m_shoeL.vtx.h \
	shape/player/mario/m_shoeL.h \
	shape/player/mario/m_thighR.vtx.h \
	shape/player/mario/m_thighR.h \
	shape/player/mario/m_shinR.vtx.h \
	shape/player/mario/m_shinR.h \
	shape/player/mario/m_shoeR.vtx.h \
	shape/player/mario/m_shoeR.h \
	shape/player/mario/m_torso0.vtx.h \
	shape/player/mario/m_torso2.vtx.h \
	shape/player/mario/m_torso1.vtx.h \
	shape/player/mario/m_torso0.h \
	shape/player/mario/m_torso1.h \
	shape/player/mario/m_torso2.h \
	shape/player/mario/l_waist.vtx.h \
	shape/player/mario/l_waist.h \
	shape/player/mario/l_uarmL.vtx.h \
	shape/player/mario/l_uarmL.h \
	shape/player/mario/l_larmL.vtx.h \
	shape/player/mario/l_larmL.h \
	shape/player/mario/l_fistL.vtx.h \
	shape/player/mario/l_fistL.h \
	shape/player/mario/l_uarmR.vtx.h \
	shape/player/mario/l_uarmR.h \
	shape/player/mario/l_larmR.vtx.h \
	shape/player/mario/l_larmR.h \
	shape/player/mario/l_fistR.vtx.h \
	shape/player/mario/l_fistR.h \
	shape/player/mario/l_thighL.vtx.h \
	shape/player/mario/l_thighL.h \
	shape/player/mario/l_shinL.vtx.h \
	shape/player/mario/l_shinL.h \
	shape/player/mario/l_shoeL.vtx.h \
	shape/player/mario/l_shoeL.h \
	shape/player/mario/l_thighR.vtx.h \
	shape/player/mario/l_thighR.h \
	shape/player/mario/l_shinR.vtx.h \
	shape/player/mario/l_shinR.h \
	shape/player/mario/l_shoeR.vtx.h \
	shape/player/mario/l_shoeR.h \
	shape/player/mario/l_torso0.vtx.h \
	shape/player/mario/l_torso1.vtx.h \
	shape/player/mario/l_torso2.vtx.h \
	shape/player/mario/l_torso0.h \
	shape/player/mario/l_torso1.h \
	shape/player/mario/l_torso2.h \
	shape/player/mario/l_cap0.vtx.h \
	shape/player/mario/l_cap1.vtx.h \
	shape/player/mario/l_cap2.vtx.h \
	shape/player/mario/l_cap4.vtx.h \
	shape/player/mario/l_cap3.vtx.h \
	shape/player/mario/l_cap5.vtx.h \
	shape/player/mario/l_cap0.h \
	shape/player/mario/l_cap1.h \
	shape/player/mario/l_cap2.h \
	shape/player/mario/l_cap3.h \
	shape/player/mario/l_cap4.h \
	shape/player/mario/l_cap5.h \
	shape/player/mario/l_hair0.vtx.h \
	shape/player/mario/l_hair1.vtx.h \
	shape/player/mario/l_hair2.vtx.h \
	shape/player/mario/l_hair3.vtx.h \
	shape/player/mario/l_hair0.h \
	shape/player/mario/l_hair1.h \
	shape/player/mario/l_hair2.h \
	shape/player/mario/l_hair3.h \
	shape/player/mario/handL.vtx.h \
	shape/player/mario/handL.h \
	shape/player/mario/handR.vtx.h \
	shape/player/mario/handR.h \
	shape/player/mario/capR0.vtx.h \
	shape/player/mario/capR2.vtx.h \
	shape/player/mario/capR1.vtx.h \
	shape/player/mario/capR3.vtx.h \
	shape/player/mario/capR0.h \
	shape/player/mario/capR1.h \
	shape/player/mario/capR2.h \
	shape/player/mario/capR3.h \
	shape/player/mario/wingsR_l.vtx.h \
	shape/player/mario/wingsR_r.vtx.h \
	shape/player/mario/wingsR_l.h \
	shape/player/mario/wingsR_r.h \
	shape/player/mario/peaceR.vtx.h \
	shape/player/mario/peaceR.h \
	shape/player/mario/cap0.vtx.h \
	shape/player/mario/cap1.vtx.h \
	shape/player/mario/cap2.vtx.h \
	shape/player/mario/cap0.h \
	shape/player/mario/cap1.h \
	shape/player/mario/cap2.h \
	shape/player/mario/wings_l.vtx.h \
	shape/player/mario/wings_r.vtx.h \
	shape/player/mario/wings_l.h \
	shape/player/mario/wings_r.h \
	shape/player/mario/wing_l.vtx.h \
	shape/player/mario/wing_r.vtx.h \
	shape/player/mario/wing_l.h \
	shape/player/mario/wing_r.h \
	shape/player/bubble/gfx.vtx.h \
	shape/player/bubble/a.rgba16.h \
	shape/player/bubble/b.rgba16.h \
	shape/player/bubble/gfx.h \
	shape/player/dust/gfx.vtx.h \
	shape/player/dust/0.ia16.h \
	shape/player/dust/1.ia16.h \
	shape/player/dust/2.ia16.h \
	shape/player/dust/3.ia16.h \
	shape/player/dust/4.ia16.h \
	shape/player/dust/5.ia16.h \
	shape/player/dust/6.ia16.h \
	shape/player/dust/gfx.h \
	shape/player/smoke/gfx.vtx.h \
	shape/player/smoke/texture.ia16.h \
	shape/player/smoke/gfx.h \
	shape/player/wave/0.ia16.h \
	shape/player/wave/1.ia16.h \
	shape/player/wave/2.ia16.h \
	shape/player/wave/3.ia16.h \
	shape/player/wave/4.ia16.h \
	shape/player/wave/5.ia16.h \
	shape/player/ripple/0.ia16.h \
	shape/player/ripple/1.ia16.h \
	shape/player/ripple/2.ia16.h \
	shape/player/ripple/3.ia16.h \
	shape/player/sparkle/gfx.vtx.h \
	shape/player/sparkle/5.rgba16.h \
	shape/player/sparkle/4.rgba16.h \
	shape/player/sparkle/3.rgba16.h \
	shape/player/sparkle/2.rgba16.h \
	shape/player/sparkle/1.rgba16.h \
	shape/player/sparkle/0.rgba16.h \
	shape/player/sparkle/gfx.h \
	shape/player/splash/gfx.vtx.h \
	shape/player/splash/0.rgba16.h \
	shape/player/splash/1.rgba16.h \
	shape/player/splash/2.rgba16.h \
	shape/player/splash/3.rgba16.h \
	shape/player/splash/4.rgba16.h \
	shape/player/splash/5.rgba16.h \
	shape/player/splash/6.rgba16.h \
	shape/player/splash/7.rgba16.h \
	shape/player/splash/gfx.h \
	shape/player/droplet/texture.rgba16.h \
	shape/player/glow/gfx.vtx.h \
	shape/player/glow/0.ia16.h \
	shape/player/glow/1.ia16.h \
	shape/player/glow/2.ia16.h \
	shape/player/glow/3.ia16.h \
	shape/player/glow/4.ia16.h \
	shape/player/glow/gfx.h

SHAPE_1B_DEP := \
	shape/1b/bully/horn.vtx.h \
	shape/1b/bully/horn.rgba16.h \
	shape/1b/bully/horn.h \
	shape/1b/bully/body_l.rgba16.h \
	shape/1b/bully/body_r.rgba16.h \
	shape/1b/bully/eye.rgba16.h \
	shape/1b/bully/shoeL.vtx.h \
	shape/1b/bully/shoeR.vtx.h \
	shape/1b/bully/eye_old.vtx.h \
	shape/1b/bully/body_old.vtx.h \
	shape/1b/bully/shoeL.h \
	shape/1b/bully/shoeR.h \
	shape/1b/bully/eye_old.h \
	shape/1b/bully/body_old.h \
	shape/1b/bully/body_l.vtx.h \
	shape/1b/bully/body_r.vtx.h \
	shape/1b/bully/body_l.h \
	shape/1b/bully/body_r.h \
	shape/1b/bully/body_big_l.vtx.h \
	shape/1b/bully/body_big_r.vtx.h \
	shape/1b/bully/body_big_l.h \
	shape/1b/bully/body_big_r.h \
	shape/1b/bully/eye.vtx.h \
	shape/1b/bully/eye.h \
	shape/1b/blargg/upper_teeth.vtx.h \
	shape/1b/blargg/upper_jaw.vtx.h \
	shape/1b/blargg/lower_teeth.vtx.h \
	shape/1b/blargg/lower_jaw.vtx.h \
	shape/1b/blargg/body.vtx.h \
	shape/1b/blargg/upper_teeth.h \
	shape/1b/blargg/upper_jaw.h \
	shape/1b/blargg/lower_teeth.h \
	shape/1b/blargg/lower_jaw.h \
	shape/1b/blargg/body.h

SHAPE_2D_DEP := \
	shape/2d/ul.ci4.h \
	shape/2d/ur.ci4.h \
	shape/2d/ll.ci4.h \
	shape/2d/lr.ci4.h \
	shape/2d/pal.rgba16.h

GLOBAL_DEP := \
	shape/global/puff/white.vtx.h \
	shape/global/puff/black.vtx.h \
	shape/global/puff/texture.ia16.h \
	shape/global/puff/white.h \
	shape/global/puff/black.h \
	shape/global/explosion/gfx.vtx.h \
	shape/global/explosion/0.rgba16.h \
	shape/global/explosion/1.rgba16.h \
	shape/global/explosion/2.rgba16.h \
	shape/global/explosion/3.rgba16.h \
	shape/global/explosion/4.rgba16.h \
	shape/global/explosion/5.rgba16.h \
	shape/global/explosion/6.rgba16.h \
	shape/global/explosion/gfx.h \
	shape/global/butterfly/l.vtx.h \
	shape/global/butterfly/wing.rgba16.h \
	shape/global/butterfly/r.vtx.h \
	shape/global/butterfly/l.h \
	shape/global/butterfly/r.h \
	shape/global/coin/0.ia16.h \
	shape/global/coin/1.ia16.h \
	shape/global/coin/2.ia16.h \
	shape/global/coin/3.ia16.h \
	shape/global/pipe/side.vtx.h \
	shape/global/pipe/side.rgba16.h \
	shape/global/pipe/side_w.i8.h \
	shape/global/pipe/side.h \
	shape/global/pipe/top.vtx.h \
	shape/global/pipe/bottom.vtx.h \
	shape/global/pipe/top.rgba16.h \
	shape/global/pipe/top_w.i8.h \
	shape/global/pipe/top.h \
	shape/global/pipe/bottom.h \
	shape/global/pipe/map.h \
	shape/global/door/a_face.rgba16.h \
	shape/global/door/a_side.rgba16.h \
	shape/global/door/b_face.rgba16.h \
	shape/global/door/b_side.rgba16.h \
	shape/global/door/d_face.rgba16.h \
	shape/global/door/d_side.rgba16.h \
	shape/global/door/e_face.rgba16.h \
	shape/global/door/e_side.rgba16.h \
	shape/global/door/f_face.rgba16.h \
	shape/global/door/f_side.rgba16.h \
	shape/global/door/star.rgba16.h \
	shape/global/door/star1.rgba16.h \
	shape/global/door/star2.rgba16.h \
	shape/global/door/star3.rgba16.h \
	shape/global/door/keyhole.rgba16.h \
	shape/global/door/a_h_side.vtx.h \
	shape/global/door/a_h_face.vtx.h \
	shape/global/door/a_h_knob_f.vtx.h \
	shape/global/door/a_h_knob_b.vtx.h \
	shape/global/door/a_h_side.h \
	shape/global/door/a_h_face.h \
	shape/global/door/a_h_knob_f.h \
	shape/global/door/a_h_knob_b.h \
	shape/global/door/a_l_face.vtx.h \
	shape/global/door/a_l_face.h \
	shape/global/door/h_side.vtx.h \
	shape/global/door/h_face.vtx.h \
	shape/global/door/h_knob.vtx.h \
	shape/global/door/h_knob.h \
	shape/global/door/h_side.h \
	shape/global/door/h_face.h \
	shape/global/door/l_panel.vtx.h \
	shape/global/door/l_knob.vtx.h \
	shape/global/door/l_panel.h \
	shape/global/door/l_knob.h \
	shape/global/doorkey/key.vtx.h \
	shape/global/doorkey/key.h \
	shape/global/flame/gfx.vtx.h \
	shape/global/flame/0.ia16.h \
	shape/global/flame/1.ia16.h \
	shape/global/flame/2.ia16.h \
	shape/global/flame/3.ia16.h \
	shape/global/flame/4.ia16.h \
	shape/global/flame/5.ia16.h \
	shape/global/flame/6.ia16.h \
	shape/global/flame/7.ia16.h \
	shape/global/flame/gfx.h \
	shape/global/fish/texture.rgba16.h \
	shape/global/fish/body.vtx.h \
	shape/global/fish/body.h \
	shape/global/fish/tail.vtx.h \
	shape/global/fish/tail.h \
	shape/global/stone/gfx.vtx.h \
	shape/global/stone/texture.rgba16.h \
	shape/global/stone/gfx.h \
	shape/global/leaf/gfx.vtx.h \
	shape/global/leaf/texture.rgba16.h \
	shape/global/leaf/gfx.h \
	shape/global/map/door.h \
	shape/global/map/13002018.h \
	shape/global/cap/metal.rgba16.h \
	shape/global/cap/logo.rgba16.h \
	shape/global/cap/wing_l.rgba16.h \
	shape/global/cap/wing_r.rgba16.h \
	shape/global/cap/metal_wing_l.rgba16.h \
	shape/global/cap/metal_wing_r.rgba16.h \
	shape/global/cap/cap0.vtx.h \
	shape/global/cap/cap1.vtx.h \
	shape/global/cap/cap2.vtx.h \
	shape/global/cap/cap0.h \
	shape/global/cap/cap1.h \
	shape/global/cap/cap2.h \
	shape/global/cap/wings_l.vtx.h \
	shape/global/cap/wings_r.vtx.h \
	shape/global/cap/wings_l.h \
	shape/global/cap/wings_r.h \
	shape/global/meter/0_l.rgba16.h \
	shape/global/meter/0_r.rgba16.h \
	shape/global/meter/8.rgba16.h \
	shape/global/meter/7.rgba16.h \
	shape/global/meter/6.rgba16.h \
	shape/global/meter/5.rgba16.h \
	shape/global/meter/4.rgba16.h \
	shape/global/meter/3.rgba16.h \
	shape/global/meter/2.rgba16.h \
	shape/global/meter/1.rgba16.h \
	shape/global/1up/texture.rgba16.h \
	shape/global/powerstar/star.rgba16.h \
	shape/global/powerstar/eye.rgba16.h \
	shape/global/powerstar/star.vtx.h \
	shape/global/powerstar/star.h \
	shape/global/powerstar/eyes.vtx.h \
	shape/global/powerstar/eyes.h \
	shape/global/sand/gfx.vtx.h \
	shape/global/sand/texture.rgba16.h \
	shape/global/sand/gfx.h \
	shape/global/shard/cork.vtx.h \
	shape/global/shard/cork.rgba16.h \
	shape/global/shard/cork.h \
	shape/global/shard/shard_s.vtx.h \
	shape/global/shard/shard_y.vtx.h \
	shape/global/shard/star_s.vtx.h \
	shape/global/shard/star_y.vtx.h \
	shape/global/shard/star_s.h \
	shape/global/shard/star_y.h \
	shape/global/shard/shard_s.h \
	shape/global/shard/shard_y.h \
	shape/global/shadowstar/star.vtx.h \
	shape/global/shadowstar/star.h \
	shape/global/snow/gfx.vtx.h \
	shape/global/snow/texture.rgba16.h \
	shape/global/snow/gfx.h \
	shape/global/signpost/post.vtx.h \
	shape/global/signpost/wood.rgba16.h \
	shape/global/signpost/face.rgba16.h \
	shape/global/signpost/post.h \
	shape/global/signpost/sign.vtx.h \
	shape/global/signpost/face.vtx.h \
	shape/global/signpost/sign.h \
	shape/global/signpost/face.h \
	shape/global/signpost/map.h \
	shape/global/tree/a_l.rgba16.h \
	shape/global/tree/a_r.rgba16.h \
	shape/global/tree/a_l.vtx.h \
	shape/global/tree/a_r.vtx.h \
	shape/global/tree/a_l.h \
	shape/global/tree/a_r.h \
	shape/global/tree/b.rgba16.h \
	shape/global/tree/b.vtx.h \
	shape/global/tree/b.h \
	shape/global/tree/c.rgba16.h \
	shape/global/tree/c.vtx.h \
	shape/global/tree/c.h \
	shape/global/tree/d.vtx.h \
	shape/global/tree/d.h \
	shape/global/tree/e.rgba16.h \
	shape/global/tree/e.vtx.h \
	shape/global/tree/e.h

TITLE_LOGO_DEP := \
	stage/title/logo/marble.vtx.h \
	stage/title/logo/wood.vtx.h \
	stage/title/logo/shade.vtx.h \
	stage/title/logo/wood.rgba16.h \
	stage/title/logo/marble.rgba16.h \
	stage/title/logo/marble.h \
	stage/title/logo/wood.h \
	stage/title/logo/shade.h \
	stage/title/symbol/copyright.vtx.h \
	stage/title/symbol/trademark.vtx.h \
	stage/title/symbol/copyright.rgba16.h \
	stage/title/symbol/trademark.rgba16.h \
	stage/title/symbol/copyright.h \
	stage/title/symbol/trademark.h

TITLE_DEBUG_DEP := \
	stage/title/debug/super_s.vtx.h \
	stage/title/debug/super_s.h \
	stage/title/debug/super_u.vtx.h \
	stage/title/debug/super_u.h \
	stage/title/debug/super_p.vtx.h \
	stage/title/debug/super_p.h \
	stage/title/debug/super_e.vtx.h \
	stage/title/debug/super_e.h \
	stage/title/debug/super_r.vtx.h \
	stage/title/debug/super_r.h \
	stage/title/debug/mario_m.vtx.h \
	stage/title/debug/mario_m.h \
	stage/title/debug/mario_a.vtx.h \
	stage/title/debug/mario_a.h \
	stage/title/debug/mario_r.vtx.h \
	stage/title/debug/mario_r.h \
	stage/title/debug/mario_i.vtx.h \
	stage/title/debug/mario_i.h \
	stage/title/debug/mario_o.vtx.h \
	stage/title/debug/mario_o.h

SELECT_DEP := \
	stage/select/file/light.rgba16.h \
	stage/select/file/shade.rgba16.h \
	stage/select/file/mario.rgba16.h \
	stage/select/file/new.rgba16.h \
	stage/select/file/edge.vtx.h \
	stage/select/file/face.vtx.h \
	stage/select/file/edge.h \
	stage/select/file/face.h \
	stage/select/file/back.vtx.h \
	stage/select/file/back.h \
	stage/select/tile/erase.rgba16.h \
	stage/select/tile/copy.rgba16.h \
	stage/select/tile/main.rgba16.h \
	stage/select/tile/score.rgba16.h \
	stage/select/tile/sound.rgba16.h \
	stage/select/tile/gfx.vtx.h \
	stage/select/tile/gfx.h \
	stage/select/cursor/0.rgba16.h \
	stage/select/cursor/1.rgba16.h \
	stage/select/print/k_hu.rgba16.h \
	stage/select/print/k_xa.rgba16.h \
	stage/select/print/k_i.rgba16.h \
	stage/select/print/k_ru.rgba16.h \
	stage/select/print/k_se.rgba16.h \
	stage/select/print/k_re.rgba16.h \
	stage/select/print/k_ku.rgba16.h \
	stage/select/print/k_to.rgba16.h \
	stage/select/print/h_wo.rgba16.h \
	stage/select/print/k_ko.rgba16.h \
	stage/select/print/k_pi.rgba16.h \
	stage/select/print/chouonpu.rgba16.h \
	stage/select/print/h_su.rgba16.h \
	stage/select/print/h_ru.rgba16.h \
	stage/select/print/h_ke.rgba16.h \
	stage/select/print/k_ma.rgba16.h \
	stage/select/print/k_ri.rgba16.h \
	stage/select/print/k_o.rgba16.h \
	stage/select/print/k_su.rgba16.h \
	stage/select/print/k_a.rgba16.h \
	stage/select/print/h_mi.rgba16.h \
	stage/select/print/h_do.rgba16.h \
	stage/select/print/h_no.rgba16.h \
	stage/select/print/question.rgba16.h \
	stage/select/print/k_sa.rgba16.h \
	stage/select/print/k_u.rgba16.h \
	stage/select/print/k_n.rgba16.h \
	stage/select/print/k_do.rgba16.h \
	stage/select/msg8/0.ia8.h \
	stage/select/msg8/1.ia8.h \
	stage/select/msg8/2.ia8.h \
	stage/select/msg8/3.ia8.h \
	stage/select/msg8/4.ia8.h \
	stage/select/msg8/5.ia8.h \
	stage/select/msg8/6.ia8.h \
	stage/select/msg8/7.ia8.h \
	stage/select/msg8/8.ia8.h \
	stage/select/msg8/9.ia8.h \
	stage/select/msg8/u_a.ia8.h \
	stage/select/msg8/u_b.ia8.h \
	stage/select/msg8/u_c.ia8.h \
	stage/select/msg8/u_d.ia8.h \
	stage/select/msg8/u_e.ia8.h \
	stage/select/msg8/u_f.ia8.h \
	stage/select/msg8/u_g.ia8.h \
	stage/select/msg8/u_h.ia8.h \
	stage/select/msg8/u_i.ia8.h \
	stage/select/msg8/u_j.ia8.h \
	stage/select/msg8/u_k.ia8.h \
	stage/select/msg8/u_l.ia8.h \
	stage/select/msg8/u_m.ia8.h \
	stage/select/msg8/u_n.ia8.h \
	stage/select/msg8/u_o.ia8.h \
	stage/select/msg8/u_p.ia8.h \
	stage/select/msg8/u_q.ia8.h \
	stage/select/msg8/u_r.ia8.h \
	stage/select/msg8/u_s.ia8.h \
	stage/select/msg8/u_t.ia8.h \
	stage/select/msg8/u_u.ia8.h \
	stage/select/msg8/u_v.ia8.h \
	stage/select/msg8/u_w.ia8.h \
	stage/select/msg8/u_x.ia8.h \
	stage/select/msg8/u_y.ia8.h \
	stage/select/msg8/u_z.ia8.h \
	stage/select/msg8/l_a.ia8.h \
	stage/select/msg8/l_c.ia8.h \
	stage/select/msg8/l_d.ia8.h \
	stage/select/msg8/l_e.ia8.h \
	stage/select/msg8/l_i.ia8.h \
	stage/select/msg8/l_m.ia8.h \
	stage/select/msg8/l_n.ia8.h \
	stage/select/msg8/l_o.ia8.h \
	stage/select/msg8/l_s.ia8.h \
	stage/select/msg8/l_u.ia8.h \
	stage/select/msg8/coin.ia8.h \
	stage/select/msg8/multiply.ia8.h \
	stage/select/msg8/paren_r.ia8.h \
	stage/select/msg8/star.ia8.h \
	stage/select/msg8/hyphen.ia8.h \
	stage/select/msg8/comma.ia8.h \
	stage/select/msg8/apostrophe.ia8.h \
	stage/select/msg8/exclaim.ia8.h \
	stage/select/msg8/question.ia8.h \
	stage/select/msg8/mario_l.ia8.h \
	stage/select/msg8/mario_r.ia8.h \
	stage/select/msg8/period.ia8.h \
	stage/select/msg8/colon.ia8.h \
	stage/select/msg8/ampersand.ia8.h \
	stage/select/msg8/hash.ia8.h \
	stage/select/course/h.rgba16.h \
	stage/select/course/l.rgba16.h \
	stage/select/map.h

BACKGROUND_TITLE_DEP := \
	data/background/title/mario.0.rgba16.h \
	data/background/title/mario.1.rgba16.h \
	data/background/title/mario.2.rgba16.h \
	data/background/title/mario.3.rgba16.h \
	data/background/title/gameover.0.rgba16.h \
	data/background/title/gameover.1.rgba16.h \
	data/background/title/gameover.2.rgba16.h \
	data/background/title/gameover.3.rgba16.h

BACKGROUND_A_DEP := \
	data/background/a/0.rgba16.h \
	data/background/a/1.rgba16.h \
	data/background/a/2.rgba16.h \
	data/background/a/3.rgba16.h \
	data/background/a/4.rgba16.h \
	data/background/a/5.rgba16.h \
	data/background/a/6.rgba16.h \
	data/background/a/7.rgba16.h \
	data/background/a/8.rgba16.h \
	data/background/a/9.rgba16.h \
	data/background/a/10.rgba16.h \
	data/background/a/11.rgba16.h \
	data/background/a/12.rgba16.h \
	data/background/a/13.rgba16.h \
	data/background/a/14.rgba16.h \
	data/background/a/15.rgba16.h \
	data/background/a/16.rgba16.h \
	data/background/a/17.rgba16.h \
	data/background/a/18.rgba16.h \
	data/background/a/19.rgba16.h \
	data/background/a/20.rgba16.h \
	data/background/a/21.rgba16.h \
	data/background/a/22.rgba16.h \
	data/background/a/23.rgba16.h \
	data/background/a/24.rgba16.h \
	data/background/a/25.rgba16.h \
	data/background/a/26.rgba16.h \
	data/background/a/27.rgba16.h \
	data/background/a/28.rgba16.h \
	data/background/a/29.rgba16.h \
	data/background/a/30.rgba16.h \
	data/background/a/31.rgba16.h \
	data/background/a/32.rgba16.h \
	data/background/a/33.rgba16.h \
	data/background/a/34.rgba16.h \
	data/background/a/35.rgba16.h \
	data/background/a/36.rgba16.h \
	data/background/a/37.rgba16.h \
	data/background/a/38.rgba16.h \
	data/background/a/39.rgba16.h \
	data/background/a/40.rgba16.h \
	data/background/a/41.rgba16.h \
	data/background/a/42.rgba16.h \
	data/background/a/43.rgba16.h \
	data/background/a/44.rgba16.h \
	data/background/a/45.rgba16.h \
	data/background/a/46.rgba16.h \
	data/background/a/47.rgba16.h \
	data/background/a/48.rgba16.h \
	data/background/a/49.rgba16.h \
	data/background/a/50.rgba16.h \
	data/background/a/51.rgba16.h \
	data/background/a/52.rgba16.h \
	data/background/a/53.rgba16.h \
	data/background/a/54.rgba16.h \
	data/background/a/55.rgba16.h \
	data/background/a/56.rgba16.h \
	data/background/a/57.rgba16.h \
	data/background/a/58.rgba16.h \
	data/background/a/59.rgba16.h \
	data/background/a/60.rgba16.h \
	data/background/a/61.rgba16.h \
	data/background/a/62.rgba16.h \
	data/background/a/63.rgba16.h

BACKGROUND_B_DEP := \
	data/background/b/0.rgba16.h \
	data/background/b/1.rgba16.h \
	data/background/b/2.rgba16.h \
	data/background/b/3.rgba16.h \
	data/background/b/4.rgba16.h \
	data/background/b/5.rgba16.h \
	data/background/b/6.rgba16.h \
	data/background/b/7.rgba16.h \
	data/background/b/8.rgba16.h \
	data/background/b/9.rgba16.h \
	data/background/b/10.rgba16.h \
	data/background/b/11.rgba16.h \
	data/background/b/12.rgba16.h \
	data/background/b/13.rgba16.h \
	data/background/b/14.rgba16.h \
	data/background/b/15.rgba16.h \
	data/background/b/16.rgba16.h \
	data/background/b/17.rgba16.h \
	data/background/b/18.rgba16.h \
	data/background/b/19.rgba16.h \
	data/background/b/20.rgba16.h \
	data/background/b/21.rgba16.h \
	data/background/b/22.rgba16.h \
	data/background/b/23.rgba16.h \
	data/background/b/24.rgba16.h \
	data/background/b/25.rgba16.h \
	data/background/b/26.rgba16.h \
	data/background/b/27.rgba16.h \
	data/background/b/28.rgba16.h \
	data/background/b/29.rgba16.h \
	data/background/b/30.rgba16.h \
	data/background/b/31.rgba16.h \
	data/background/b/32.rgba16.h \
	data/background/b/33.rgba16.h \
	data/background/b/34.rgba16.h \
	data/background/b/35.rgba16.h \
	data/background/b/36.rgba16.h \
	data/background/b/37.rgba16.h \
	data/background/b/38.rgba16.h \
	data/background/b/39.rgba16.h \
	data/background/b/40.rgba16.h \
	data/background/b/41.rgba16.h \
	data/background/b/42.rgba16.h \
	data/background/b/43.rgba16.h \
	data/background/b/44.rgba16.h \
	data/background/b/45.rgba16.h \
	data/background/b/46.rgba16.h \
	data/background/b/47.rgba16.h \
	data/background/b/48.rgba16.h \
	data/background/b/49.rgba16.h \
	data/background/b/50.rgba16.h \
	data/background/b/51.rgba16.h \
	data/background/b/52.rgba16.h \
	data/background/b/53.rgba16.h \
	data/background/b/54.rgba16.h \
	data/background/b/55.rgba16.h \
	data/background/b/56.rgba16.h \
	data/background/b/57.rgba16.h \
	data/background/b/58.rgba16.h \
	data/background/b/59.rgba16.h \
	data/background/b/60.rgba16.h \
	data/background/b/61.rgba16.h \
	data/background/b/62.rgba16.h \
	data/background/b/63.rgba16.h

BACKGROUND_C_DEP := \
	data/background/c/0.rgba16.h \
	data/background/c/1.rgba16.h \
	data/background/c/2.rgba16.h \
	data/background/c/3.rgba16.h \
	data/background/c/4.rgba16.h \
	data/background/c/5.rgba16.h \
	data/background/c/6.rgba16.h \
	data/background/c/7.rgba16.h \
	data/background/c/8.rgba16.h \
	data/background/c/9.rgba16.h \
	data/background/c/10.rgba16.h \
	data/background/c/11.rgba16.h \
	data/background/c/12.rgba16.h \
	data/background/c/13.rgba16.h \
	data/background/c/14.rgba16.h \
	data/background/c/15.rgba16.h \
	data/background/c/16.rgba16.h \
	data/background/c/17.rgba16.h \
	data/background/c/18.rgba16.h \
	data/background/c/19.rgba16.h \
	data/background/c/20.rgba16.h \
	data/background/c/21.rgba16.h \
	data/background/c/22.rgba16.h \
	data/background/c/23.rgba16.h \
	data/background/c/24.rgba16.h \
	data/background/c/25.rgba16.h \
	data/background/c/26.rgba16.h \
	data/background/c/27.rgba16.h \
	data/background/c/28.rgba16.h \
	data/background/c/29.rgba16.h \
	data/background/c/30.rgba16.h \
	data/background/c/31.rgba16.h \
	data/background/c/32.rgba16.h \
	data/background/c/33.rgba16.h \
	data/background/c/34.rgba16.h \
	data/background/c/35.rgba16.h \
	data/background/c/36.rgba16.h \
	data/background/c/37.rgba16.h \
	data/background/c/38.rgba16.h \
	data/background/c/39.rgba16.h \
	data/background/c/40.rgba16.h

BACKGROUND_D_DEP := \
	data/background/d/0.rgba16.h \
	data/background/d/1.rgba16.h \
	data/background/d/2.rgba16.h \
	data/background/d/3.rgba16.h \
	data/background/d/4.rgba16.h \
	data/background/d/5.rgba16.h \
	data/background/d/6.rgba16.h \
	data/background/d/7.rgba16.h \
	data/background/d/8.rgba16.h \
	data/background/d/9.rgba16.h \
	data/background/d/10.rgba16.h \
	data/background/d/11.rgba16.h \
	data/background/d/12.rgba16.h \
	data/background/d/13.rgba16.h \
	data/background/d/14.rgba16.h \
	data/background/d/15.rgba16.h \
	data/background/d/16.rgba16.h \
	data/background/d/17.rgba16.h \
	data/background/d/18.rgba16.h \
	data/background/d/19.rgba16.h \
	data/background/d/20.rgba16.h \
	data/background/d/21.rgba16.h \
	data/background/d/22.rgba16.h \
	data/background/d/23.rgba16.h \
	data/background/d/24.rgba16.h \
	data/background/d/25.rgba16.h \
	data/background/d/26.rgba16.h \
	data/background/d/27.rgba16.h \
	data/background/d/28.rgba16.h \
	data/background/d/29.rgba16.h \
	data/background/d/30.rgba16.h \
	data/background/d/31.rgba16.h \
	data/background/d/32.rgba16.h \
	data/background/d/33.rgba16.h \
	data/background/d/34.rgba16.h \
	data/background/d/35.rgba16.h \
	data/background/d/36.rgba16.h \
	data/background/d/37.rgba16.h \
	data/background/d/38.rgba16.h \
	data/background/d/39.rgba16.h \
	data/background/d/40.rgba16.h \
	data/background/d/41.rgba16.h \
	data/background/d/42.rgba16.h \
	data/background/d/43.rgba16.h \
	data/background/d/44.rgba16.h \
	data/background/d/45.rgba16.h \
	data/background/d/46.rgba16.h \
	data/background/d/47.rgba16.h \
	data/background/d/48.rgba16.h

BACKGROUND_E_DEP := \
	data/background/e/0.rgba16.h \
	data/background/e/1.rgba16.h \
	data/background/e/2.rgba16.h \
	data/background/e/3.rgba16.h \
	data/background/e/4.rgba16.h \
	data/background/e/5.rgba16.h \
	data/background/e/6.rgba16.h \
	data/background/e/7.rgba16.h \
	data/background/e/8.rgba16.h \
	data/background/e/9.rgba16.h \
	data/background/e/10.rgba16.h \
	data/background/e/11.rgba16.h \
	data/background/e/12.rgba16.h \
	data/background/e/13.rgba16.h \
	data/background/e/14.rgba16.h \
	data/background/e/15.rgba16.h \
	data/background/e/16.rgba16.h \
	data/background/e/17.rgba16.h \
	data/background/e/18.rgba16.h \
	data/background/e/19.rgba16.h \
	data/background/e/20.rgba16.h \
	data/background/e/21.rgba16.h \
	data/background/e/22.rgba16.h \
	data/background/e/23.rgba16.h \
	data/background/e/24.rgba16.h \
	data/background/e/25.rgba16.h \
	data/background/e/26.rgba16.h \
	data/background/e/27.rgba16.h \
	data/background/e/28.rgba16.h \
	data/background/e/29.rgba16.h \
	data/background/e/30.rgba16.h \
	data/background/e/31.rgba16.h \
	data/background/e/32.rgba16.h \
	data/background/e/33.rgba16.h \
	data/background/e/34.rgba16.h \
	data/background/e/35.rgba16.h \
	data/background/e/36.rgba16.h \
	data/background/e/37.rgba16.h \
	data/background/e/38.rgba16.h \
	data/background/e/39.rgba16.h \
	data/background/e/40.rgba16.h \
	data/background/e/41.rgba16.h \
	data/background/e/42.rgba16.h \
	data/background/e/43.rgba16.h \
	data/background/e/44.rgba16.h \
	data/background/e/45.rgba16.h \
	data/background/e/46.rgba16.h \
	data/background/e/47.rgba16.h \
	data/background/e/48.rgba16.h \
	data/background/e/49.rgba16.h \
	data/background/e/50.rgba16.h \
	data/background/e/51.rgba16.h \
	data/background/e/52.rgba16.h \
	data/background/e/53.rgba16.h \
	data/background/e/54.rgba16.h \
	data/background/e/55.rgba16.h \
	data/background/e/56.rgba16.h \
	data/background/e/57.rgba16.h \
	data/background/e/58.rgba16.h \
	data/background/e/59.rgba16.h \
	data/background/e/60.rgba16.h \
	data/background/e/61.rgba16.h \
	data/background/e/62.rgba16.h \
	data/background/e/63.rgba16.h

BACKGROUND_F_DEP := \
	data/background/f/0.rgba16.h \
	data/background/f/1.rgba16.h \
	data/background/f/2.rgba16.h \
	data/background/f/3.rgba16.h \
	data/background/f/4.rgba16.h \
	data/background/f/5.rgba16.h \
	data/background/f/6.rgba16.h \
	data/background/f/7.rgba16.h \
	data/background/f/8.rgba16.h \
	data/background/f/9.rgba16.h \
	data/background/f/10.rgba16.h \
	data/background/f/11.rgba16.h \
	data/background/f/12.rgba16.h \
	data/background/f/13.rgba16.h \
	data/background/f/14.rgba16.h \
	data/background/f/15.rgba16.h \
	data/background/f/16.rgba16.h \
	data/background/f/17.rgba16.h \
	data/background/f/18.rgba16.h \
	data/background/f/19.rgba16.h \
	data/background/f/20.rgba16.h \
	data/background/f/21.rgba16.h \
	data/background/f/22.rgba16.h \
	data/background/f/23.rgba16.h \
	data/background/f/24.rgba16.h \
	data/background/f/25.rgba16.h \
	data/background/f/26.rgba16.h \
	data/background/f/27.rgba16.h \
	data/background/f/28.rgba16.h \
	data/background/f/29.rgba16.h \
	data/background/f/30.rgba16.h \
	data/background/f/31.rgba16.h \
	data/background/f/32.rgba16.h \
	data/background/f/33.rgba16.h \
	data/background/f/34.rgba16.h \
	data/background/f/35.rgba16.h \
	data/background/f/36.rgba16.h \
	data/background/f/37.rgba16.h \
	data/background/f/38.rgba16.h \
	data/background/f/39.rgba16.h \
	data/background/f/40.rgba16.h \
	data/background/f/41.rgba16.h \
	data/background/f/42.rgba16.h \
	data/background/f/43.rgba16.h \
	data/background/f/44.rgba16.h \
	data/background/f/45.rgba16.h \
	data/background/f/46.rgba16.h \
	data/background/f/47.rgba16.h \
	data/background/f/48.rgba16.h \
	data/background/f/49.rgba16.h \
	data/background/f/50.rgba16.h \
	data/background/f/51.rgba16.h \
	data/background/f/52.rgba16.h \
	data/background/f/53.rgba16.h \
	data/background/f/54.rgba16.h \
	data/background/f/55.rgba16.h \
	data/background/f/56.rgba16.h \
	data/background/f/57.rgba16.h \
	data/background/f/58.rgba16.h \
	data/background/f/59.rgba16.h \
	data/background/f/60.rgba16.h \
	data/background/f/61.rgba16.h \
	data/background/f/62.rgba16.h \
	data/background/f/63.rgba16.h

BACKGROUND_G_DEP := \
	data/background/g/0.rgba16.h \
	data/background/g/1.rgba16.h \
	data/background/g/2.rgba16.h \
	data/background/g/3.rgba16.h \
	data/background/g/4.rgba16.h \
	data/background/g/5.rgba16.h \
	data/background/g/6.rgba16.h \
	data/background/g/7.rgba16.h \
	data/background/g/8.rgba16.h \
	data/background/g/9.rgba16.h \
	data/background/g/10.rgba16.h \
	data/background/g/11.rgba16.h \
	data/background/g/12.rgba16.h \
	data/background/g/13.rgba16.h \
	data/background/g/14.rgba16.h \
	data/background/g/15.rgba16.h \
	data/background/g/16.rgba16.h \
	data/background/g/17.rgba16.h \
	data/background/g/18.rgba16.h \
	data/background/g/19.rgba16.h \
	data/background/g/20.rgba16.h \
	data/background/g/21.rgba16.h \
	data/background/g/22.rgba16.h \
	data/background/g/23.rgba16.h \
	data/background/g/24.rgba16.h \
	data/background/g/25.rgba16.h \
	data/background/g/26.rgba16.h \
	data/background/g/27.rgba16.h \
	data/background/g/28.rgba16.h \
	data/background/g/29.rgba16.h \
	data/background/g/30.rgba16.h \
	data/background/g/31.rgba16.h \
	data/background/g/32.rgba16.h \
	data/background/g/33.rgba16.h \
	data/background/g/34.rgba16.h \
	data/background/g/35.rgba16.h \
	data/background/g/36.rgba16.h \
	data/background/g/37.rgba16.h \
	data/background/g/38.rgba16.h \
	data/background/g/39.rgba16.h \
	data/background/g/40.rgba16.h \
	data/background/g/41.rgba16.h \
	data/background/g/42.rgba16.h \
	data/background/g/43.rgba16.h \
	data/background/g/44.rgba16.h \
	data/background/g/45.rgba16.h \
	data/background/g/46.rgba16.h \
	data/background/g/47.rgba16.h \
	data/background/g/48.rgba16.h \
	data/background/g/49.rgba16.h \
	data/background/g/50.rgba16.h \
	data/background/g/51.rgba16.h \
	data/background/g/52.rgba16.h \
	data/background/g/53.rgba16.h \
	data/background/g/54.rgba16.h \
	data/background/g/55.rgba16.h \
	data/background/g/56.rgba16.h \
	data/background/g/57.rgba16.h \
	data/background/g/58.rgba16.h \
	data/background/g/59.rgba16.h \
	data/background/g/60.rgba16.h \
	data/background/g/61.rgba16.h \
	data/background/g/62.rgba16.h \
	data/background/g/63.rgba16.h

BACKGROUND_H_DEP := \
	data/background/h/0.rgba16.h \
	data/background/h/1.rgba16.h \
	data/background/h/2.rgba16.h \
	data/background/h/3.rgba16.h \
	data/background/h/4.rgba16.h \
	data/background/h/5.rgba16.h \
	data/background/h/6.rgba16.h \
	data/background/h/7.rgba16.h \
	data/background/h/8.rgba16.h \
	data/background/h/9.rgba16.h \
	data/background/h/10.rgba16.h \
	data/background/h/11.rgba16.h \
	data/background/h/12.rgba16.h \
	data/background/h/13.rgba16.h \
	data/background/h/14.rgba16.h \
	data/background/h/15.rgba16.h \
	data/background/h/16.rgba16.h \
	data/background/h/17.rgba16.h \
	data/background/h/18.rgba16.h \
	data/background/h/19.rgba16.h \
	data/background/h/20.rgba16.h \
	data/background/h/21.rgba16.h \
	data/background/h/22.rgba16.h \
	data/background/h/23.rgba16.h \
	data/background/h/24.rgba16.h \
	data/background/h/25.rgba16.h \
	data/background/h/26.rgba16.h \
	data/background/h/27.rgba16.h \
	data/background/h/28.rgba16.h \
	data/background/h/29.rgba16.h \
	data/background/h/30.rgba16.h \
	data/background/h/31.rgba16.h \
	data/background/h/32.rgba16.h \
	data/background/h/33.rgba16.h \
	data/background/h/34.rgba16.h \
	data/background/h/35.rgba16.h \
	data/background/h/36.rgba16.h \
	data/background/h/37.rgba16.h \
	data/background/h/38.rgba16.h \
	data/background/h/39.rgba16.h \
	data/background/h/40.rgba16.h

BACKGROUND_I_DEP := \
	data/background/i/0.rgba16.h \
	data/background/i/1.rgba16.h \
	data/background/i/2.rgba16.h \
	data/background/i/3.rgba16.h \
	data/background/i/4.rgba16.h \
	data/background/i/5.rgba16.h \
	data/background/i/6.rgba16.h \
	data/background/i/7.rgba16.h \
	data/background/i/8.rgba16.h \
	data/background/i/9.rgba16.h \
	data/background/i/10.rgba16.h \
	data/background/i/11.rgba16.h \
	data/background/i/12.rgba16.h \
	data/background/i/13.rgba16.h \
	data/background/i/14.rgba16.h \
	data/background/i/15.rgba16.h \
	data/background/i/16.rgba16.h \
	data/background/i/17.rgba16.h \
	data/background/i/18.rgba16.h \
	data/background/i/19.rgba16.h \
	data/background/i/20.rgba16.h \
	data/background/i/21.rgba16.h \
	data/background/i/22.rgba16.h \
	data/background/i/23.rgba16.h \
	data/background/i/24.rgba16.h \
	data/background/i/25.rgba16.h \
	data/background/i/26.rgba16.h \
	data/background/i/27.rgba16.h \
	data/background/i/28.rgba16.h \
	data/background/i/29.rgba16.h \
	data/background/i/30.rgba16.h \
	data/background/i/31.rgba16.h \
	data/background/i/32.rgba16.h \
	data/background/i/33.rgba16.h \
	data/background/i/34.rgba16.h \
	data/background/i/35.rgba16.h \
	data/background/i/36.rgba16.h \
	data/background/i/37.rgba16.h \
	data/background/i/38.rgba16.h \
	data/background/i/39.rgba16.h \
	data/background/i/40.rgba16.h \
	data/background/i/41.rgba16.h \
	data/background/i/42.rgba16.h \
	data/background/i/43.rgba16.h \
	data/background/i/44.rgba16.h \
	data/background/i/45.rgba16.h \
	data/background/i/46.rgba16.h \
	data/background/i/47.rgba16.h \
	data/background/i/48.rgba16.h \
	data/background/i/49.rgba16.h \
	data/background/i/50.rgba16.h \
	data/background/i/51.rgba16.h \
	data/background/i/52.rgba16.h \
	data/background/i/53.rgba16.h \
	data/background/i/54.rgba16.h \
	data/background/i/55.rgba16.h \
	data/background/i/56.rgba16.h \
	data/background/i/57.rgba16.h \
	data/background/i/58.rgba16.h \
	data/background/i/59.rgba16.h \
	data/background/i/60.rgba16.h \
	data/background/i/61.rgba16.h \
	data/background/i/62.rgba16.h \
	data/background/i/63.rgba16.h

BACKGROUND_J_DEP := \
	data/background/j/0.rgba16.h \
	data/background/j/1.rgba16.h \
	data/background/j/2.rgba16.h \
	data/background/j/3.rgba16.h \
	data/background/j/4.rgba16.h \
	data/background/j/5.rgba16.h \
	data/background/j/6.rgba16.h \
	data/background/j/7.rgba16.h \
	data/background/j/8.rgba16.h \
	data/background/j/9.rgba16.h \
	data/background/j/10.rgba16.h \
	data/background/j/11.rgba16.h \
	data/background/j/12.rgba16.h \
	data/background/j/13.rgba16.h \
	data/background/j/14.rgba16.h \
	data/background/j/15.rgba16.h \
	data/background/j/16.rgba16.h \
	data/background/j/17.rgba16.h \
	data/background/j/18.rgba16.h \
	data/background/j/19.rgba16.h \
	data/background/j/20.rgba16.h \
	data/background/j/21.rgba16.h \
	data/background/j/22.rgba16.h \
	data/background/j/23.rgba16.h \
	data/background/j/24.rgba16.h \
	data/background/j/25.rgba16.h \
	data/background/j/26.rgba16.h \
	data/background/j/27.rgba16.h \
	data/background/j/28.rgba16.h \
	data/background/j/29.rgba16.h \
	data/background/j/30.rgba16.h \
	data/background/j/31.rgba16.h \
	data/background/j/32.rgba16.h \
	data/background/j/33.rgba16.h \
	data/background/j/34.rgba16.h \
	data/background/j/35.rgba16.h \
	data/background/j/36.rgba16.h \
	data/background/j/37.rgba16.h \
	data/background/j/38.rgba16.h \
	data/background/j/39.rgba16.h \
	data/background/j/40.rgba16.h \
	data/background/j/41.rgba16.h \
	data/background/j/42.rgba16.h \
	data/background/j/43.rgba16.h \
	data/background/j/44.rgba16.h \
	data/background/j/45.rgba16.h \
	data/background/j/46.rgba16.h \
	data/background/j/47.rgba16.h \
	data/background/j/48.rgba16.h \
	data/background/j/49.rgba16.h \
	data/background/j/50.rgba16.h \
	data/background/j/51.rgba16.h \
	data/background/j/52.rgba16.h \
	data/background/j/53.rgba16.h \
	data/background/j/54.rgba16.h \
	data/background/j/55.rgba16.h \
	data/background/j/56.rgba16.h \
	data/background/j/57.rgba16.h \
	data/background/j/58.rgba16.h \
	data/background/j/59.rgba16.h \
	data/background/j/60.rgba16.h \
	data/background/j/61.rgba16.h \
	data/background/j/62.rgba16.h \
	data/background/j/63.rgba16.h

TEXTURE_A_DEP := \
	data/texture/a0.rgba16.h \
	data/texture/a1.rgba16.h \
	data/texture/a2.rgba16.h \
	data/texture/a3.rgba16.h \
	data/texture/a4.rgba16.h \
	data/texture/a5.rgba16.h \
	data/texture/a6.rgba16.h \
	data/texture/a7.rgba16.h \
	data/texture/a8.rgba16.h \
	data/texture/a9.rgba16.h \
	data/texture/a10.rgba16.h \
	data/texture/a11.rgba16.h \
	data/texture/a12.rgba16.h \
	data/texture/a13.rgba16.h \
	data/texture/a14.rgba16.h \
	data/texture/a15.rgba16.h \
	data/texture/a16.rgba16.h \
	data/texture/a17.rgba16.h \
	data/texture/a18.rgba16.h \
	data/texture/a19.rgba16.h \
	data/texture/a20.rgba16.h \
	data/texture/a21.rgba16.h \
	data/texture/a22.rgba16.h \
	data/texture/a23.rgba16.h

TEXTURE_B_DEP := \
	data/texture/b0.rgba16.h \
	data/texture/b1.rgba16.h \
	data/texture/b2.rgba16.h \
	data/texture/b3.rgba16.h \
	data/texture/b4.rgba16.h \
	data/texture/b5.rgba16.h \
	data/texture/b6.rgba16.h \
	data/texture/b7.rgba16.h \
	data/texture/b8.rgba16.h \
	data/texture/b9.rgba16.h \
	data/texture/b10.rgba16.h \
	data/texture/b11.rgba16.h \
	data/texture/b12.rgba16.h \
	data/texture/b13.rgba16.h \
	data/texture/b14.rgba16.h \
	data/texture/b15_g17.ia16.h \
	data/texture/b16.ia16.h \
	data/texture/b17.ia16.h

TEXTURE_C_DEP := \
	data/texture/c0.rgba16.h \
	data/texture/c1.rgba16.h \
	data/texture/c2.rgba16.h \
	data/texture/c3.rgba16.h \
	data/texture/c4.rgba16.h \
	data/texture/c5.rgba16.h \
	data/texture/c6.rgba16.h \
	data/texture/c7.rgba16.h \
	data/texture/c8.rgba16.h \
	data/texture/c9.rgba16.h \
	data/texture/c10.rgba16.h \
	data/texture/c11.rgba16.h \
	data/texture/c12.rgba16.h \
	data/texture/c13.rgba16.h \
	data/texture/c14.rgba16.h \
	data/texture/c15.rgba16.h \
	data/texture/c16.rgba16.h \
	data/texture/c17.rgba16.h \
	data/texture/c18.rgba16.h \
	data/texture/c19.rgba16.h \
	data/texture/c20.rgba16.h \
	data/texture/c21_j22_k22.ia16.h

TEXTURE_D_DEP := \
	data/texture/d0.rgba16.h \
	data/texture/d1.rgba16.h \
	data/texture/d2.rgba16.h \
	data/texture/d3.rgba16.h \
	data/texture/d4.rgba16.h \
	data/texture/d5.rgba16.h \
	data/texture/d6.rgba16.h \
	data/texture/d7.rgba16.h \
	data/texture/d8.rgba16.h \
	data/texture/d9.rgba16.h \
	data/texture/d10.rgba16.h \
	data/texture/d11.rgba16.h \
	data/texture/d12.rgba16.h \
	data/texture/d13.rgba16.h \
	data/texture/d14.rgba16.h

TEXTURE_E_DEP := \
	data/texture/e0.rgba16.h \
	data/texture/e1.rgba16.h \
	data/texture/e2.rgba16.h \
	data/texture/e3.rgba16.h \
	data/texture/e4.rgba16.h \
	data/texture/e5.rgba16.h \
	data/texture/e6.rgba16.h \
	data/texture/e7.rgba16.h \
	data/texture/e8_j12.rgba16.h \
	data/texture/e9.rgba16.h \
	data/texture/e10_i18.rgba16.h \
	data/texture/e11.rgba16.h \
	data/texture/e12.rgba16.h \
	data/texture/e13.rgba16.h \
	data/texture/e14.rgba16.h

TEXTURE_F_DEP := \
	data/texture/f0.rgba16.h \
	data/texture/f1.rgba16.h \
	data/texture/f2.rgba16.h \
	data/texture/f3.rgba16.h \
	data/texture/f4.rgba16.h \
	data/texture/f5.rgba16.h \
	data/texture/f6.rgba16.h \
	data/texture/f7.rgba16.h \
	data/texture/f8.rgba16.h \
	data/texture/f9.rgba16.h \
	data/texture/f10.rgba16.h \
	data/texture/f11.rgba16.h \
	data/texture/f12.rgba16.h \
	data/texture/f13.rgba16.h \
	data/texture/f14.rgba16.h \
	data/texture/f15.rgba16.h \
	data/texture/f16.ia16.h \
	data/texture/f17.ia16.h

TEXTURE_G_DEP := \
	data/texture/g0.rgba16.h \
	data/texture/g1.rgba16.h \
	data/texture/g2.rgba16.h \
	data/texture/g3.rgba16.h \
	data/texture/g4.rgba16.h \
	data/texture/g5.rgba16.h \
	data/texture/g6.rgba16.h \
	data/texture/g7.rgba16.h \
	data/texture/g8.rgba16.h \
	data/texture/g9.rgba16.h \
	data/texture/g10.rgba16.h \
	data/texture/g11.rgba16.h \
	data/texture/g12.rgba16.h \
	data/texture/g13.rgba16.h \
	data/texture/g14.rgba16.h \
	data/texture/g15.rgba16.h \
	data/texture/g16.ia16.h \
	data/texture/b15_g17.ia16.h

TEXTURE_H_DEP := \
	data/texture/h0.rgba16.h \
	data/texture/h1_l6.rgba16.h \
	data/texture/h2.rgba16.h \
	data/texture/h3.rgba16.h \
	data/texture/h4.rgba16.h \
	data/texture/h5.rgba16.h \
	data/texture/h6.rgba16.h \
	data/texture/h7.rgba16.h \
	data/texture/h8.rgba16.h \
	data/texture/h9.rgba16.h \
	data/texture/h10.rgba16.h \
	data/texture/h11.rgba16.h \
	data/texture/h12.rgba16.h \
	data/texture/h13.rgba16.h \
	data/texture/h14.rgba16.h \
	data/texture/h15.rgba16.h \
	data/texture/h16.rgba16.h

TEXTURE_I_DEP := \
	data/texture/i0.rgba16.h \
	data/texture/i1.rgba16.h \
	data/texture/i2.rgba16.h \
	data/texture/i3.rgba16.h \
	data/texture/i4.rgba16.h \
	data/texture/i5.rgba16.h \
	data/texture/i6.rgba16.h \
	data/texture/i7.rgba16.h \
	data/texture/i8.rgba16.h \
	data/texture/i9.rgba16.h \
	data/texture/i10.rgba16.h \
	data/texture/i11.rgba16.h \
	data/texture/i12.rgba16.h \
	data/texture/i13.rgba16.h \
	data/texture/i14.rgba16.h \
	data/texture/i15.rgba16.h \
	data/texture/i16.rgba16.h \
	data/texture/i17.rgba16.h \
	data/texture/e10_i18.rgba16.h \
	data/texture/i19.rgba16.h \
	data/texture/i20.rgba16.h \
	data/texture/i21.rgba16.h \
	data/texture/i22.rgba16.h

TEXTURE_J_DEP := \
	data/texture/j0.rgba16.h \
	data/texture/j1.rgba16.h \
	data/texture/j2.rgba16.h \
	data/texture/j3.rgba16.h \
	data/texture/j4.rgba16.h \
	data/texture/j5.rgba16.h \
	data/texture/j6.rgba16.h \
	data/texture/j7.rgba16.h \
	data/texture/j8.rgba16.h \
	data/texture/j9.rgba16.h \
	data/texture/j10.rgba16.h \
	data/texture/j11.rgba16.h \
	data/texture/e8_j12.rgba16.h \
	data/texture/j13.rgba16.h \
	data/texture/j14.rgba16.h \
	data/texture/j15.rgba16.h \
	data/texture/j16.rgba16.h \
	data/texture/j17.rgba16.h \
	data/texture/j18.rgba16.h \
	data/texture/j19.rgba16.h \
	data/texture/j20.rgba16.h \
	data/texture/j21.rgba16.h \
	data/texture/c21_j22_k22.ia16.h \
	data/texture/j23.ia16.h

TEXTURE_K_DEP := \
	data/texture/k0.rgba16.h \
	data/texture/k1.rgba16.h \
	data/texture/k2.rgba16.h \
	data/texture/k3.rgba16.h \
	data/texture/k4.rgba16.h \
	data/texture/k5.rgba16.h \
	data/texture/k6.rgba16.h \
	data/texture/k7.rgba16.h \
	data/texture/k8.rgba16.h \
	data/texture/k9.rgba16.h \
	data/texture/k10.rgba16.h \
	data/texture/k11.rgba16.h \
	data/texture/k12.rgba16.h \
	data/texture/k13.rgba16.h \
	data/texture/k14.rgba16.h \
	data/texture/k15.rgba16.h \
	data/texture/k16.rgba16.h \
	data/texture/k17.rgba16.h \
	data/texture/k18.rgba16.h \
	data/texture/k19.rgba16.h \
	data/texture/k20.rgba16.h \
	data/texture/k21.rgba16.h \
	data/texture/c21_j22_k22.ia16.h

TEXTURE_L_DEP := \
	data/texture/l0.rgba16.h \
	data/texture/l1.rgba16.h \
	data/texture/l2.rgba16.h \
	data/texture/l3.rgba16.h \
	data/texture/l4.rgba16.h \
	data/texture/l5.rgba16.h \
	data/texture/h1_l6.rgba16.h \
	data/texture/l7.rgba16.h \
	data/texture/l8.rgba16.h \
	data/texture/l9.rgba16.h \
	data/texture/l10.rgba16.h \
	data/texture/l11.rgba16.h \
	data/texture/l12.rgba16.h \
	data/texture/l13.rgba16.h \
	data/texture/l14.rgba16.h \
	data/texture/l15.rgba16.h \
	data/texture/l16.rgba16.h \
	data/texture/l17.rgba16.h

WEATHER_DEP := \
	data/weather/flower/0.rgba16.h \
	data/weather/flower/1.rgba16.h \
	data/weather/flower/2.rgba16.h \
	data/weather/flower/3.rgba16.h \
	data/weather/lava/0.rgba16.h \
	data/weather/lava/1.rgba16.h \
	data/weather/lava/2.rgba16.h \
	data/weather/lava/3.rgba16.h \
	data/weather/lava/4.rgba16.h \
	data/weather/lava/5.rgba16.h \
	data/weather/lava/6.rgba16.h \
	data/weather/lava/7.rgba16.h \
	data/weather/bubble/0.rgba16.h \
	data/weather/snow/a.rgba16.h \
	data/weather/snow/b.rgba16.h

PAINT_DEP := \
	stage/paint/banner.i4.h \
	stage/paint/clear.i4.h \
	stage/paint/done.rgba16.h \
	stage/paint/tool.ci4.h \
	stage/paint/tool.rgba16.h

STAGE1_DEP := \
	data/texture/d3.rgba16.h \
	data/texture/d5.rgba16.h \
	data/texture/d9.rgba16.h \
	stage/stage1/throwback/B_biank_liv_si4.i4.h \
	stage/stage1/throwback/B_mokume_brown.ci4.h \
	stage/stage1/throwback/B_mokume_whiteS.ci4.h \
	stage/stage1/throwback/B_mokume_brown.rgba16.h \
	stage/stage1/throwback/B_mokume_whiteS.rgba16.h \
	stage/stage1/throwback/shade.vtx.h \
	stage/stage1/throwback/c4.vtx.h \
	stage/stage1/throwback/c11.vtx.h \
	stage/stage1/throwback/c17.vtx.h \
	stage/stage1/throwback/c18.vtx.h \
	stage/stage1/throwback/d3.vtx.h \
	stage/stage1/throwback/d5.vtx.h \
	stage/stage1/throwback/d9.vtx.h \
	stage/stage1/throwback/B_biank_liv_si4.vtx.h \
	stage/stage1/throwback/B_mokume_brown.vtx.h \
	stage/stage1/throwback/B_mokume_whiteS.vtx.h \
	stage/stage1/throwback/shade.h \
	stage/stage1/throwback/c4.h \
	stage/stage1/throwback/c11.h \
	stage/stage1/throwback/c17.h \
	stage/stage1/throwback/c18.h \
	stage/stage1/throwback/d3.h \
	stage/stage1/throwback/d5.h \
	stage/stage1/throwback/d9.h \
	stage/stage1/throwback/B_biank_liv_si4.h \
	stage/stage1/throwback/B_mokume_brown.h \
	stage/stage1/throwback/B_mokume_whiteS.h \
	stage/stage1/teleport/texture.rgba16.h \
	stage/stage1/teleport/gfx.vtx.h \
	stage/stage1/teleport/gfx.h \
	stage/stage1/chest2/0.rgba16.h \
	stage/stage1/chest2/1.rgba16.h \
	stage/stage1/chest2/2.rgba16.h \
	stage/stage1/chest2/3.rgba16.h \
	stage/stage1/chest2/0.vtx.h \
	stage/stage1/chest2/1.vtx.h \
	stage/stage1/chest2/2.vtx.h \
	stage/stage1/chest2/3.vtx.h \
	stage/stage1/chest2/0.h \
	stage/stage1/chest2/1.h \
	stage/stage1/chest2/2.h \
	stage/stage1/chest2/3.h \
	stage/stage1/chest2/4.vtx.h \
	stage/stage1/chest2/5.vtx.h \
	stage/stage1/chest2/6.vtx.h \
	stage/stage1/chest2/4.h \
	stage/stage1/chest2/5.h \
	stage/stage1/chest2/6.h \
	stage/stage1/throwback/map.h

STAGE2_DEP := \
	stage/stage2/a8.rgba16.h \
	stage/stage2/retro/ground.rgba16.h \
	stage/stage2/retro/shade.vtx.h \
	stage/stage2/retro/ground.vtx.h \
	stage/stage2/retro/lava.vtx.h \
	stage/stage2/retro/shade.h \
	stage/stage2/retro/ground.h \
	stage/stage2/retro/lava.h \
	stage/stage2/retro/a8.vtx.h \
	stage/stage2/retro/kparrow.vtx.h \
	stage/stage2/retro/kpground.vtx.h \
	stage/stage2/retro/kpwall.vtx.h \
	stage/stage2/retro/a8.h \
	stage/stage2/retro/kparrow.h \
	stage/stage2/retro/kpground.h \
	stage/stage2/retro/kpwall.h \
	stage/stage2/retrolift/texture.rgba16.h \
	stage/stage2/retrolift/gfxA.vtx.h \
	stage/stage2/retrolift/gfxB.vtx.h \
	stage/stage2/retrolift/gfxA.h \
	stage/stage2/retrolift/gfxB.h \
	stage/stage2/retro/map.h \
	stage/stage2/retrolift/mapA.h \
	stage/stage2/retrolift/mapB.h

STAGE3_DEP := \
	stage/stage3/chamber/wall.vtx.h \
	stage/stage3/chamber/ground.vtx.h \
	stage/stage3/chamber/roof.vtx.h \
	stage/stage3/chamber/wall.h \
	stage/stage3/chamber/ground.h \
	stage/stage3/chamber/roof.h \
	stage/stage3/chamber/map.h

BOB_DEP := \
	stage/bob/0.rgba16.h \
	stage/bob/1.rgba16.h \
	stage/bob/2.rgba16.h \
	stage/bob/3.rgba16.h \
	stage/bob/4.rgba16.h \
	stage/bob/battlefield/0.vtx.h \
	stage/bob/battlefield/1.vtx.h \
	stage/bob/battlefield/2.vtx.h \
	stage/bob/battlefield/0.h \
	stage/bob/battlefield/1.h \
	stage/bob/battlefield/2.h \
	stage/bob/battlefield/3.vtx.h \
	stage/bob/battlefield/4.vtx.h \
	stage/bob/battlefield/5.vtx.h \
	stage/bob/battlefield/6.vtx.h \
	stage/bob/battlefield/7.vtx.h \
	stage/bob/battlefield/8.vtx.h \
	stage/bob/battlefield/9.vtx.h \
	stage/bob/battlefield/10.vtx.h \
	stage/bob/battlefield/11.vtx.h \
	stage/bob/battlefield/12.vtx.h \
	stage/bob/battlefield/3.h \
	stage/bob/battlefield/4.h \
	stage/bob/battlefield/5.h \
	stage/bob/battlefield/6.h \
	stage/bob/battlefield/7.h \
	stage/bob/battlefield/8.h \
	stage/bob/battlefield/9.h \
	stage/bob/battlefield/10.h \
	stage/bob/battlefield/11.h \
	stage/bob/battlefield/12.h \
	stage/bob/battlefield/13.vtx.h \
	stage/bob/battlefield/13.h \
	stage/bob/battlefield/14.vtx.h \
	stage/bob/battlefield/15.vtx.h \
	stage/bob/battlefield/14.h \
	stage/bob/battlefield/15.h \
	stage/bob/battlefield/16.vtx.h \
	stage/bob/battlefield/17.vtx.h \
	stage/bob/battlefield/18.vtx.h \
	stage/bob/battlefield/19.vtx.h \
	stage/bob/battlefield/20.vtx.h \
	stage/bob/battlefield/21.vtx.h \
	stage/bob/battlefield/22.vtx.h \
	stage/bob/battlefield/16.h \
	stage/bob/battlefield/17.h \
	stage/bob/battlefield/18.h \
	stage/bob/battlefield/19.h \
	stage/bob/battlefield/20.h \
	stage/bob/battlefield/21.h \
	stage/bob/battlefield/22.h \
	stage/bob/battlefield/23.vtx.h \
	stage/bob/battlefield/23.h \
	stage/bob/54/54.vtx.h \
	stage/bob/54/54.h \
	stage/bob/55/55.vtx.h \
	stage/bob/55/55.h \
	stage/bob/56/56.vtx.h \
	stage/bob/56/56.h \
	stage/bob/battlefield/map.h \
	stage/bob/54/map.h \
	stage/bob/55/map.h \
	stage/bob/56/map.h

ENDING_DEP := \
	stage/ending/texture.i4.h

CHANGE_DEP := \
	data/video/change/0.rgba16.h \
	data/video/change/1.rgba16.h \
	data/video/change/2.rgba16.h \
	data/video/change/3.rgba16.h \
	data/video/change/4.rgba16.h \
	data/video/change/5.rgba16.h \
	data/video/change/6.rgba16.h \
	data/video/change/7.rgba16.h \
	data/video/change/8.rgba16.h \
	data/video/change/9.rgba16.h \
	data/video/change/10.rgba16.h \
	data/video/change/11.rgba16.h \
	data/video/change/12.rgba16.h \
	data/video/change/13.rgba16.h \
	data/video/change/14.rgba16.h \
	data/video/change/15.rgba16.h \
	data/video/change/16.rgba16.h \
	data/video/change/17.rgba16.h \
	data/video/change/18.rgba16.h \
	data/video/change/19.rgba16.h \
	data/video/change/20.rgba16.h \
	data/video/change/21.rgba16.h \
	data/video/change/22.rgba16.h \
	data/video/change/23.rgba16.h \
	data/video/change/24.rgba16.h \
	data/video/change/25.rgba16.h \
	data/video/change/26.rgba16.h \
	data/video/change/27.rgba16.h \
	data/video/change/28.rgba16.h \
	data/video/change/29.rgba16.h \
	data/video/change/30.rgba16.h \
	data/video/change/31.rgba16.h \
	data/video/change/32.rgba16.h \
	data/video/change/33.rgba16.h \
	data/video/change/34.rgba16.h \
	data/video/change/35.rgba16.h \
	data/video/change/36.rgba16.h \
	data/video/change/37.rgba16.h \
	data/video/change/38.rgba16.h \
	data/video/change/39.rgba16.h \
	data/video/change/40.rgba16.h \
	data/video/change/41.rgba16.h \
	data/video/change/42.rgba16.h \
	data/video/change/43.rgba16.h \
	data/video/change/44.rgba16.h \
	data/video/change/45.rgba16.h \
	data/video/change/46.rgba16.h \
	data/video/change/47.rgba16.h \
	data/video/change/48.rgba16.h \
	data/video/change/49.rgba16.h \
	data/video/change/50.rgba16.h \
	data/video/change/51.rgba16.h \
	data/video/change/52.rgba16.h \
	data/video/change/53.rgba16.h \
	data/video/change/54.rgba16.h \
	data/video/change/55.rgba16.h \
	data/video/change/56.rgba16.h \
	data/video/change/57.rgba16.h \
	data/video/change/58.rgba16.h \
	data/video/change/59.rgba16.h \
	data/video/change/60.rgba16.h \
	data/video/change/61.rgba16.h \
	data/video/change/62.rgba16.h \
	data/video/change/63.rgba16.h \
	data/video/change/64.rgba16.h \
	data/video/change/65.rgba16.h \
	data/video/change/66.rgba16.h \
	data/video/change/67.rgba16.h \
	data/video/change/68.rgba16.h \
	data/video/change/69.rgba16.h \
	data/video/change/70.rgba16.h \
	data/video/change/71.rgba16.h \
	data/video/change/72.rgba16.h \
	data/video/change/73.rgba16.h \
	data/video/change/74.rgba16.h \
	data/video/change/75.rgba16.h \
	data/video/change/76.rgba16.h \
	data/video/change/77.rgba16.h \
	data/video/change/78.rgba16.h \
	data/video/change/79.rgba16.h \
	data/video/change/80.rgba16.h \
	data/video/change/81.rgba16.h \
	data/video/change/82.rgba16.h \
	data/video/change/83.rgba16.h \
	data/video/change/84.rgba16.h \
	data/video/change/85.rgba16.h

MOVIE_DEP := \
	data/video/Movie/0.rgba16.h \
	data/video/Movie/1.rgba16.h \
	data/video/Movie/2.rgba16.h \
	data/video/Movie/3.rgba16.h \
	data/video/Movie/4.rgba16.h \
	data/video/Movie/5.rgba16.h \
	data/video/Movie/6.rgba16.h \
	data/video/Movie/7.rgba16.h \
	data/video/Movie/8.rgba16.h \
	data/video/Movie/9.rgba16.h \
	data/video/Movie/10.rgba16.h \
	data/video/Movie/11.rgba16.h \
	data/video/Movie/12.rgba16.h \
	data/video/Movie/13.rgba16.h \
	data/video/Movie/14.rgba16.h \
	data/video/Movie/15.rgba16.h \
	data/video/Movie/16.rgba16.h \
	data/video/Movie/17.rgba16.h \
	data/video/Movie/18.rgba16.h \
	data/video/Movie/19.rgba16.h \
	data/video/Movie/20.rgba16.h \
	data/video/Movie/21.rgba16.h \
	data/video/Movie/22.rgba16.h \
	data/video/Movie/23.rgba16.h \
	data/video/Movie/24.rgba16.h \
	data/video/Movie/25.rgba16.h \
	data/video/Movie/26.rgba16.h \
	data/video/Movie/27.rgba16.h \
	data/video/Movie/28.rgba16.h \
	data/video/Movie/29.rgba16.h \
	data/video/Movie/30.rgba16.h \
	data/video/Movie/31.rgba16.h \
	data/video/Movie/32.rgba16.h \
	data/video/Movie/33.rgba16.h \
	data/video/Movie/34.rgba16.h \
	data/video/Movie/35.rgba16.h \
	data/video/Movie/36.rgba16.h \
	data/video/Movie/37.rgba16.h \
	data/video/Movie/38.rgba16.h \
	data/video/Movie/39.rgba16.h \
	data/video/Movie/40.rgba16.h \
	data/video/Movie/41.rgba16.h \
	data/video/Movie/42.rgba16.h \
	data/video/Movie/43.rgba16.h \
	data/video/Movie/44.rgba16.h \
	data/video/Movie/45.rgba16.h \
	data/video/Movie/46.rgba16.h \
	data/video/Movie/47.rgba16.h \
	data/video/Movie/48.rgba16.h \
	data/video/Movie/49.rgba16.h \
	data/video/Movie/50.rgba16.h \
	data/video/Movie/51.rgba16.h

SCATMAN_DEP := \
	data/video/scatman/0.rgba16.h \
	data/video/scatman/1.rgba16.h \
	data/video/scatman/2.rgba16.h \
	data/video/scatman/3.rgba16.h \
	data/video/scatman/4.rgba16.h \
	data/video/scatman/5.rgba16.h \
	data/video/scatman/6.rgba16.h \
	data/video/scatman/7.rgba16.h \
	data/video/scatman/8.rgba16.h \
	data/video/scatman/9.rgba16.h \
	data/video/scatman/10.rgba16.h \
	data/video/scatman/11.rgba16.h \
	data/video/scatman/12.rgba16.h \
	data/video/scatman/13.rgba16.h \
	data/video/scatman/14.rgba16.h \
	data/video/scatman/15.rgba16.h \
	data/video/scatman/16.rgba16.h \
	data/video/scatman/17.rgba16.h \
	data/video/scatman/18.rgba16.h \
	data/video/scatman/19.rgba16.h \
	data/video/scatman/20.rgba16.h \
	data/video/scatman/21.rgba16.h \
	data/video/scatman/22.rgba16.h \
	data/video/scatman/23.rgba16.h \
	data/video/scatman/24.rgba16.h \
	data/video/scatman/25.rgba16.h \
	data/video/scatman/26.rgba16.h \
	data/video/scatman/27.rgba16.h \
	data/video/scatman/28.rgba16.h \
	data/video/scatman/29.rgba16.h \
	data/video/scatman/30.rgba16.h \
	data/video/scatman/31.rgba16.h \
	data/video/scatman/32.rgba16.h \
	data/video/scatman/33.rgba16.h \
	data/video/scatman/34.rgba16.h \
	data/video/scatman/35.rgba16.h \
	data/video/scatman/36.rgba16.h \
	data/video/scatman/37.rgba16.h \
	data/video/scatman/38.rgba16.h \
	data/video/scatman/39.rgba16.h \
	data/video/scatman/40.rgba16.h \
	data/video/scatman/41.rgba16.h \
	data/video/scatman/42.rgba16.h \
	data/video/scatman/43.rgba16.h \
	data/video/scatman/44.rgba16.h \
	data/video/scatman/45.rgba16.h \
	data/video/scatman/46.rgba16.h \
	data/video/scatman/47.rgba16.h \
	data/video/scatman/48.rgba16.h \
	data/video/scatman/49.rgba16.h \
	data/video/scatman/50.rgba16.h \
	data/video/scatman/51.rgba16.h \
	data/video/scatman/52.rgba16.h \
	data/video/scatman/53.rgba16.h \
	data/video/scatman/54.rgba16.h \
	data/video/scatman/55.rgba16.h \
	data/video/scatman/56.rgba16.h \
	data/video/scatman/57.rgba16.h \
	data/video/scatman/58.rgba16.h \
	data/video/scatman/59.rgba16.h \
	data/video/scatman/60.rgba16.h \
	data/video/scatman/61.rgba16.h \
	data/video/scatman/62.rgba16.h \
	data/video/scatman/63.rgba16.h \
	data/video/scatman/64.rgba16.h \
	data/video/scatman/65.rgba16.h \
	data/video/scatman/66.rgba16.h \
	data/video/scatman/67.rgba16.h \
	data/video/scatman/68.rgba16.h \
	data/video/scatman/69.rgba16.h \
	data/video/scatman/70.rgba16.h \
	data/video/scatman/71.rgba16.h \
	data/video/scatman/72.rgba16.h \
	data/video/scatman/73.rgba16.h \
	data/video/scatman/74.rgba16.h \
	data/video/scatman/75.rgba16.h \
	data/video/scatman/76.rgba16.h \
	data/video/scatman/77.rgba16.h \
	data/video/scatman/78.rgba16.h \
	data/video/scatman/79.rgba16.h \
	data/video/scatman/80.rgba16.h \
	data/video/scatman/81.rgba16.h \
	data/video/scatman/82.rgba16.h \
	data/video/scatman/83.rgba16.h \
	data/video/scatman/84.rgba16.h \
	data/video/scatman/85.rgba16.h \
	data/video/scatman/86.rgba16.h \
	data/video/scatman/87.rgba16.h \
	data/video/scatman/88.rgba16.h \
	data/video/scatman/89.rgba16.h \
	data/video/scatman/90.rgba16.h \
	data/video/scatman/91.rgba16.h \
	data/video/scatman/92.rgba16.h \
	data/video/scatman/93.rgba16.h \
	data/video/scatman/94.rgba16.h \
	data/video/scatman/95.rgba16.h \
	data/video/scatman/96.rgba16.h \
	data/video/scatman/97.rgba16.h \
	data/video/scatman/98.rgba16.h \
	data/video/scatman/99.rgba16.h \
	data/video/scatman/100.rgba16.h \
	data/video/scatman/101.rgba16.h \
	data/video/scatman/102.rgba16.h \
	data/video/scatman/103.rgba16.h \
	data/video/scatman/104.rgba16.h \
	data/video/scatman/105.rgba16.h \
	data/video/scatman/106.rgba16.h \
	data/video/scatman/107.rgba16.h \
	data/video/scatman/108.rgba16.h \
	data/video/scatman/109.rgba16.h \
	data/video/scatman/110.rgba16.h \
	data/video/scatman/111.rgba16.h \
	data/video/scatman/112.rgba16.h \
	data/video/scatman/113.rgba16.h \
	data/video/scatman/114.rgba16.h \
	data/video/scatman/115.rgba16.h \
	data/video/scatman/116.rgba16.h \
	data/video/scatman/117.rgba16.h \
	data/video/scatman/118.rgba16.h \
	data/video/scatman/119.rgba16.h \
	data/video/scatman/120.rgba16.h \
	data/video/scatman/121.rgba16.h \
	data/video/scatman/122.rgba16.h \
	data/video/scatman/123.rgba16.h \
	data/video/scatman/124.rgba16.h \
	data/video/scatman/125.rgba16.h \
	data/video/scatman/126.rgba16.h \
	data/video/scatman/127.rgba16.h \
	data/video/scatman/128.rgba16.h \
	data/video/scatman/129.rgba16.h \
	data/video/scatman/130.rgba16.h \
	data/video/scatman/131.rgba16.h \
	data/video/scatman/132.rgba16.h \
	data/video/scatman/133.rgba16.h \
	data/video/scatman/134.rgba16.h \
	data/video/scatman/135.rgba16.h \
	data/video/scatman/136.rgba16.h \
	data/video/scatman/137.rgba16.h \
	data/video/scatman/138.rgba16.h \
	data/video/scatman/139.rgba16.h \
	data/video/scatman/140.rgba16.h \
	data/video/scatman/141.rgba16.h \
	data/video/scatman/142.rgba16.h \
	data/video/scatman/143.rgba16.h \
	data/video/scatman/144.rgba16.h \
	data/video/scatman/145.rgba16.h \
	data/video/scatman/146.rgba16.h \
	data/video/scatman/147.rgba16.h \
	data/video/scatman/148.rgba16.h \
	data/video/scatman/149.rgba16.h \
	data/video/scatman/150.rgba16.h \
	data/video/scatman/151.rgba16.h \
	data/video/scatman/152.rgba16.h \
	data/video/scatman/153.rgba16.h \
	data/video/scatman/154.rgba16.h \
	data/video/scatman/155.rgba16.h \
	data/video/scatman/156.rgba16.h \
	data/video/scatman/157.rgba16.h \
	data/video/scatman/158.rgba16.h \
	data/video/scatman/159.rgba16.h \
	data/video/scatman/160.rgba16.h \
	data/video/scatman/161.rgba16.h \
	data/video/scatman/162.rgba16.h \
	data/video/scatman/163.rgba16.h \
	data/video/scatman/164.rgba16.h \
	data/video/scatman/165.rgba16.h \
	data/video/scatman/166.rgba16.h \
	data/video/scatman/167.rgba16.h \
	data/video/scatman/168.rgba16.h \
	data/video/scatman/169.rgba16.h \
	data/video/scatman/170.rgba16.h \
	data/video/scatman/171.rgba16.h \
	data/video/scatman/172.rgba16.h \
	data/video/scatman/173.rgba16.h \
	data/video/scatman/174.rgba16.h \
	data/video/scatman/175.rgba16.h \
	data/video/scatman/176.rgba16.h \
	data/video/scatman/177.rgba16.h \
	data/video/scatman/178.rgba16.h \
	data/video/scatman/179.rgba16.h \
	data/video/scatman/180.rgba16.h \
	data/video/scatman/181.rgba16.h \
	data/video/scatman/182.rgba16.h \
	data/video/scatman/183.rgba16.h \
	data/video/scatman/184.rgba16.h \
	data/video/scatman/185.rgba16.h \
	data/video/scatman/186.rgba16.h \
	data/video/scatman/187.rgba16.h \
	data/video/scatman/188.rgba16.h \
	data/video/scatman/189.rgba16.h \
	data/video/scatman/190.rgba16.h \
	data/video/scatman/191.rgba16.h \
	data/video/scatman/192.rgba16.h \
	data/video/scatman/193.rgba16.h \
	data/video/scatman/194.rgba16.h \
	data/video/scatman/195.rgba16.h \
	data/video/scatman/196.rgba16.h \
	data/video/scatman/197.rgba16.h \
	data/video/scatman/198.rgba16.h \
	data/video/scatman/199.rgba16.h \
	data/video/scatman/200.rgba16.h \
	data/video/scatman/201.rgba16.h \
	data/video/scatman/202.rgba16.h \
	data/video/scatman/203.rgba16.h \
	data/video/scatman/204.rgba16.h \
	data/video/scatman/205.rgba16.h \
	data/video/scatman/206.rgba16.h \
	data/video/scatman/207.rgba16.h \
	data/video/scatman/208.rgba16.h

DEP := \
	src/str.h \
	src/803315E4.h \
	src/new/level2.h \
	$(GFX_DEP) \
	$(SETUP_DEP) \
	$(AVATAR_DEP) \
	$(PLAYER_DEP) \
	$(SHAPE_1B_DEP) \
	$(SHAPE_2D_DEP) \
	$(GLOBAL_DEP) \
	$(TITLE_LOGO_DEP) \
	$(TITLE_DEBUG_DEP) \
	$(SELECT_DEP) \
	$(BACKGROUND_TITLE_DEP) \
	$(BACKGROUND_A_DEP) \
	$(BACKGROUND_B_DEP) \
	$(BACKGROUND_C_DEP) \
	$(BACKGROUND_D_DEP) \
	$(BACKGROUND_E_DEP) \
	$(BACKGROUND_F_DEP) \
	$(BACKGROUND_G_DEP) \
	$(BACKGROUND_H_DEP) \
	$(BACKGROUND_I_DEP) \
	$(BACKGROUND_J_DEP) \
	$(TEXTURE_A_DEP) \
	$(TEXTURE_B_DEP) \
	$(TEXTURE_C_DEP) \
	$(TEXTURE_D_DEP) \
	$(TEXTURE_E_DEP) \
	$(TEXTURE_F_DEP) \
	$(TEXTURE_G_DEP) \
	$(TEXTURE_H_DEP) \
	$(TEXTURE_I_DEP) \
	$(TEXTURE_J_DEP) \
	$(TEXTURE_K_DEP) \
	$(TEXTURE_L_DEP) \
	$(WEATHER_DEP) \
	$(PAINT_DEP) \
	$(STAGE1_DEP) \
	$(STAGE2_DEP) \
	$(STAGE3_DEP) \
	$(BOB_DEP) \
	$(ENDING_DEP) \
	$(CHANGE_DEP) \
	$(MOVIE_DEP) \
	$(SCATMAN_DEP)

src/message.data.c: src/str.h src/803315E4.h
src/file_select.data.c: src/str.h
src/star_select.data.c: src/str.h
src/new.c: src/new/level2.h

data/gfx.c: $(GFX_DEP)
data/setup.c: $(SETUP_DEP)
data/avatar.c: $(AVATAR_DEP)
shape/player/gfx.c: $(PLAYER_DEP)
shape/1b/gfx.c: $(SHAPE_1B_DEP)
shape/2d/gfxB.c: $(SHAPE_2D_DEP)
shape/global/gfx.c: $(GLOBAL_DEP)
stage/title/logo.c: $(TITLE_LOGO_DEP)
stage/title/debug.c: $(TITLE_DEBUG_DEP)
stage/select/gfx.c: $(SELECT_DEP)
data/background/title.c: $(BACKGROUND_TITLE_DEP)
data/background/a.c: $(BACKGROUND_A_DEP)
data/background/b.c: $(BACKGROUND_B_DEP)
data/background/c.c: $(BACKGROUND_C_DEP)
data/background/d.c: $(BACKGROUND_D_DEP)
data/background/e.c: $(BACKGROUND_E_DEP)
data/background/f.c: $(BACKGROUND_F_DEP)
data/background/g.c: $(BACKGROUND_G_DEP)
data/background/h.c: $(BACKGROUND_H_DEP)
data/background/i.c: $(BACKGROUND_I_DEP)
data/background/j.c: $(BACKGROUND_J_DEP)
data/texture/a.c: $(TEXTURE_A_DEP)
data/texture/b.c: $(TEXTURE_B_DEP)
data/texture/c.c: $(TEXTURE_C_DEP)
data/texture/d.c: $(TEXTURE_D_DEP)
data/texture/e.c: $(TEXTURE_E_DEP)
data/texture/f.c: $(TEXTURE_F_DEP)
data/texture/g.c: $(TEXTURE_G_DEP)
data/texture/h.c: $(TEXTURE_H_DEP)
data/texture/i.c: $(TEXTURE_I_DEP)
data/texture/j.c: $(TEXTURE_J_DEP)
data/texture/k.c: $(TEXTURE_K_DEP)
data/texture/l.c: $(TEXTURE_L_DEP)
data/weather/gfx.c: $(WEATHER_DEP)
stage/paint/gfx.c: $(PAINT_DEP)
stage/stage1/gfx.c: $(STAGE1_DEP)
stage/stage2/gfx.c: $(STAGE2_DEP)
stage/stage3/gfx.c: $(STAGE3_DEP)
stage/bob/gfx.c: $(BOB_DEP)
stage/ending/gfx.c: $(ENDING_DEP)
data/video/change.c: $(CHANGE_DEP)
data/video/Movie.c: $(MOVIE_DEP)
data/video/scatman.c: $(SCATMAN_DEP)
