#ifndef __SM64_DEFOBJECT_H__
#define __SM64_DEFOBJECT_H__

#define O_TYPE_PLAYER           0
#define O_TYPE_PL_ATTACK        2
#define O_TYPE_ENEMYA           4
#define O_TYPE_ENEMYB           5
#define O_TYPE_ITEM             6
#define O_TYPE_DEFAULT          8
#define O_TYPE_MOVEBG           9
#define O_TYPE_PL_USE           10
#define O_TYPE_SYSTEM           11
#define O_TYPE_EFFECT           12

#define O_VAR               0
#define O_FLAG              1
#define O_MSG               2
#define O_COL_TIMER         5
#define O_POS_X             6
#define O_POS_Y             7
#define O_POS_Z             8
#define O_VEL_X             9
#define O_VEL_Y             10
#define O_VEL_Z             11
#define O_VEL_F             12
#define O_VEL_L             13
#define O_VEL_U             14
#define O_ANG_X             15
#define O_ANG_Y             16
#define O_ANG_Z             17
#define O_SHAPE_ANG_X       18
#define O_SHAPE_ANG_Y       19
#define O_SHAPE_ANG_Z       20
#define O_SHAPE_OFF_Y       21
#define O_PARTICLE          22
#define O_GRAVITY           23
#define O_GROUND_Y          24
#define O_MOVE_FLAG         25
#define O_ANIME_CODE        26
#define O_V0                27
#define O_V1                28
#define O_V2                29
#define O_V3                30
#define O_V4                31
#define O_V5                32
#define O_V6                33
#define O_V7                34
#define O_ANG_VEL_X         35
#define O_ANG_VEL_Y         36
#define O_ANG_VEL_Z         37
#define O_ANIME             38
#define O_HOLD              39
#define O_WALL_R            40
#define O_DRAG              41
#define O_COL_TYPE          42
#define O_COL_FLAG          43
#define O_OFF_X             44
#define O_OFF_Y             45
#define O_OFF_Z             46
#define O_CODE              47
#define O_STATE             49
#define O_MODE              50
#define O_TIMER             51
#define O_BOUNCE            52
#define O_PL_DIST           53
#define O_PL_ANG            54
#define O_ORG_X             55
#define O_ORG_Y             56
#define O_ORG_Z             57
#define O_FRICTION          58
#define O_DENSITY           59
#define O_ANIME_INDEX       60
#define O_ALPHA             61
#define O_AP                62
#define O_HP                63
#define O_ARG               64
#define O_STATE_PREV        65
#define O_COL_ARG           66
#define O_COL_DIST          67
#define O_COIN              68
#define O_SHAPE_DIST        69
#define O_AREA              70
#define O_PRG_ARG           72
#define O_V8                73
#define O_V9                74
#define O_WALL_ANG          75
#define O_GROUND_ARG        76
#define O_ORG_ANG           77
#define O_GROUND            78
#define O_SE_DIE            79

#endif /* __SM64_DEFOBJECT_H__ */
