#include <sm64/s_script.h>

S_SCRIPT s_1c_86[] =
{
	s_shadow(300, 150, 1),
	s_push(),
		s_scale(0.25),
		s_push(),
			s_joint(OPA_SURF, NULL, 0, 0, 0),
			s_push(),
				s_joint(OPA_SURF, NULL, 0, 0, 0),
				s_push(),
					s_joint(OPA_SURF, NULL, 0, 0, 0),
					s_push(),
						s_billboard(0, 0, 0),
						s_push(),
							s_gfx(TEX_EDGE, 0x0500B188),
						s_pull(),
					s_pull(),
					s_joint(OPA_SURF, NULL, 0, -243, 0),
					s_push(),
						s_joint(OPA_SURF, NULL, 0, 0, 0),
						s_push(),
							s_joint(OPA_SURF, NULL, 488, 0, 0),
							s_push(),
								s_joint(OPA_SURF, NULL, 110, 0, 0),
								s_push(),
									s_joint(OPA_SURF, 0x0500AD08, 0, 0, 0),
								s_pull(),
								s_joint(OPA_SURF, NULL, 0, 0, 0),
								s_push(),
									s_billboard(0, 0, 0),
									s_push(),
										s_gfx(TEX_EDGE, 0x0500A5D8),
									s_pull(),
								s_pull(),
							s_pull(),
						s_pull(),
					s_pull(),
					s_joint(TEX_EDGE, 0x0500B2D0, 0, 0, 0),
					s_joint(OPA_SURF, 0x0500B418, 0, 0, 0),
					s_joint(OPA_SURF, 0x0500B6C0, 0, 0, 0),
					s_joint(OPA_SURF, NULL, 0, 243, 0),
					s_push(),
						s_joint(OPA_SURF, NULL, 0, 0, 0),
						s_push(),
							s_joint(OPA_SURF, NULL, 488, 0, 0),
							s_push(),
								s_joint(OPA_SURF, NULL, 110, 0, 0),
								s_push(),
									s_joint(OPA_SURF, 0x0500B068, 0, 0, 0),
								s_pull(),
								s_joint(OPA_SURF, NULL, 0, 0, 0),
								s_push(),
									s_billboard(0, 0, 0),
									s_push(),
										s_gfx(TEX_EDGE, 0x0500A890),
									s_pull(),
								s_pull(),
							s_pull(),
						s_pull(),
					s_pull(),
					s_joint(OPA_SURF, NULL, 0, -1, 36),
					s_push(),
						s_joint(OPA_SURF, NULL, 0, 0, 0),
						s_push(),
							s_joint(OPA_SURF, NULL, 548, 0, 0),
							s_push(),
								s_joint(OPA_SURF, NULL, 0, 0, 0),
								s_push(),
									s_billboard(0, 0, 0),
									s_push(),
										s_gfx(TEX_EDGE, 0x0500A4F0),
									s_pull(),
								s_pull(),
								s_joint(OPA_SURF, NULL, 189, 0, 0),
								s_push(),
									s_joint(OPA_SURF, NULL, 0, 0, 0),
									s_push(),
										s_billboard(0, 0, 0),
										s_push(),
											s_gfx(TEX_EDGE, 0x0500A6C0),
										s_pull(),
									s_pull(),
									s_callback(0, s_object_a_802A719C),
								s_pull(),
							s_pull(),
						s_pull(),
					s_pull(),
					s_joint(OPA_SURF, NULL, 0, 1, 36),
					s_push(),
						s_joint(OPA_SURF, NULL, 0, 0, 0),
						s_push(),
							s_joint(OPA_SURF, NULL, 548, 0, 0),
							s_push(),
								s_joint(OPA_SURF, NULL, 0, 0, 0),
								s_push(),
									s_billboard(0, 0, 0),
									s_push(),
										s_gfx(TEX_EDGE, 0x0500A7A8),
									s_pull(),
								s_pull(),
								s_joint(OPA_SURF, NULL, 189, 0, 0),
								s_push(),
									s_joint(OPA_SURF, NULL, 0, 0, 0),
									s_push(),
										s_billboard(0, 0, 0),
										s_push(),
											s_gfx(TEX_EDGE, 0x0500A978),
										s_pull(),
									s_pull(),
								s_pull(),
							s_pull(),
						s_pull(),
					s_pull(),
				s_pull(),
			s_pull(),
		s_pull(),
	s_pull(),
	s_pull(),
	s_exit(),
};

S_SCRIPT s_1c_84[] =
{
	s_cull(150),
	s_push(),
		s_push(),
			s_gfx(XLU_SURF, 0x05011000),
		s_pull(),
	s_pull(),
	s_exit(),
};

S_SCRIPT s_1c_85[] =
{
	s_cull(150),
	s_push(),
		s_shadow(160, 100, 1),
	s_pull(),
	s_exit(),
};
