#!/usr/bin/env python3

import sys

if len(sys.argv) != 3:
	print("usage: %s <output> <input>" % sys.argv[0])
	sys.exit(1)
with open(sys.argv[2], "r") as f:
	tbl = []
	ln = 0
	for line in f:
		ln += 1
		line = line.strip()
		if not line: continue
		bnk = []
		for x in line.split():
			if not x.isdigit():
				print("%s:%d: syntax error" % (sys.argv[2], ln))
				sys.exit(1)
			bnk.append(int(x))
		tbl.append(bnk)
with open(sys.argv[1], "w") as f:
	f.write(".data\n")
	ptr = 2*len(tbl)
	for bnk in tbl:
		f.write(".short %d\n" % ptr)
		ptr += 1+len(bnk)
	for bnk in tbl:
		f.write(".byte %s\n" % ", ".join([
			"%d" % x for x in [len(bnk)]+bnk
		]))
